server:
  port: ":8003"
  base_path: "/api/v1"
  log:
    level: "debug"
    format: "text"

jwt:
  access_token:
    secret_key: "f6tD7wVYNvXMm4MwqivfpB9Gf+HYz8a3"
    token_lifetime: 900

rabbit:
  url: "amqp://localhost:5672/"
  user: "re-news"
  password: "Test@1234"
  exchange: "re-news.subscription-tracker"

database:
  sql:
    url: "postgresql://postgres:postgres@localhost:5555/postgres?sslmode=disable"
  mongo:
    uri: "mongodb://localhost:27017"
    name: "re-flow"
  cloudinary:
    cloud_name: "example"
    api_key: "example"
    api_secret: "example"
  redis:
    addr: "localhost:6379"
    password: "example"
    db: 0

swagger:
  enabled: true
  url: "/swagger"
  port: "8080"


