version: "3.8"

services:
  subscriptions-tracker:
    build: .
    container_name: subscriptions-tracker
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8003:8003"
    networks:
      - re-news-net

  subscriptions-tracker-postgres:
    image: postgres:15
    container_name: subscriptions-tracker-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7003:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - re-news-net

  subscriptions-tracker-redis:
    image: redis:6
    container_name: subscriptions-tracker-redis
    ports:
      - "7203:6379"
    networks:
      - re-news-net

networks:
  re-news-net:
    driver: bridge

volumes:
  pgdata:
