/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingSchedulesCollectionDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingSchedulesCollectionDataInner{}

// BillingSchedulesCollectionDataInner struct for BillingSchedulesCollectionDataInner
type BillingSchedulesCollectionDataInner struct {
	// schedules ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes Attributes `json:"attributes"`
}

type _BillingSchedulesCollectionDataInner BillingSchedulesCollectionDataInner

// NewBillingSchedulesCollectionDataInner instantiates a new BillingSchedulesCollectionDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingSchedulesCollectionDataInner(id string, type_ string, attributes Attributes) *BillingSchedulesCollectionDataInner {
	this := BillingSchedulesCollectionDataInner{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewBillingSchedulesCollectionDataInnerWithDefaults instantiates a new BillingSchedulesCollectionDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingSchedulesCollectionDataInnerWithDefaults() *BillingSchedulesCollectionDataInner {
	this := BillingSchedulesCollectionDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *BillingSchedulesCollectionDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollectionDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BillingSchedulesCollectionDataInner) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *BillingSchedulesCollectionDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollectionDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BillingSchedulesCollectionDataInner) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *BillingSchedulesCollectionDataInner) GetAttributes() Attributes {
	if o == nil {
		var ret Attributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollectionDataInner) GetAttributesOk() (*Attributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *BillingSchedulesCollectionDataInner) SetAttributes(v Attributes) {
	o.Attributes = v
}

func (o BillingSchedulesCollectionDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingSchedulesCollectionDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *BillingSchedulesCollectionDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingSchedulesCollectionDataInner := _BillingSchedulesCollectionDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingSchedulesCollectionDataInner)

	if err != nil {
		return err
	}

	*o = BillingSchedulesCollectionDataInner(varBillingSchedulesCollectionDataInner)

	return err
}

type NullableBillingSchedulesCollectionDataInner struct {
	value *BillingSchedulesCollectionDataInner
	isSet bool
}

func (v NullableBillingSchedulesCollectionDataInner) Get() *BillingSchedulesCollectionDataInner {
	return v.value
}

func (v *NullableBillingSchedulesCollectionDataInner) Set(val *BillingSchedulesCollectionDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingSchedulesCollectionDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingSchedulesCollectionDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingSchedulesCollectionDataInner(val *BillingSchedulesCollectionDataInner) *NullableBillingSchedulesCollectionDataInner {
	return &NullableBillingSchedulesCollectionDataInner{value: val, isSet: true}
}

func (v NullableBillingSchedulesCollectionDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingSchedulesCollectionDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


