/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubPlan{}

// SubPlan struct for SubPlan
type SubPlan struct {
	Data SubPlanData `json:"data"`
}

type _SubPlan SubPlan

// NewSubPlan instantiates a new SubPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubPlan(data SubPlanData) *SubPlan {
	this := SubPlan{}
	this.Data = data
	return &this
}

// NewSubPlanWithDefaults instantiates a new SubPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubPlanWithDefaults() *SubPlan {
	this := SubPlan{}
	return &this
}

// GetData returns the Data field value
func (o *SubPlan) GetData() SubPlanData {
	if o == nil {
		var ret SubPlanData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubPlan) GetDataOk() (*SubPlanData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubPlan) SetData(v SubPlanData) {
	o.Data = v
}

func (o SubPlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubPlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubPlan := _SubPlan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubPlan)

	if err != nil {
		return err
	}

	*o = SubPlan(varSubPlan)

	return err
}

type NullableSubPlan struct {
	value *SubPlan
	isSet bool
}

func (v NullableSubPlan) Get() *SubPlan {
	return v.value
}

func (v *NullableSubPlan) Set(val *SubPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableSubPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableSubPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubPlan(val *SubPlan) *NullableSubPlan {
	return &NullableSubPlan{value: val, isSet: true}
}

func (v NullableSubPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


