/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeCreateData{}

// SubscriptionTypeCreateData struct for SubscriptionTypeCreateData
type SubscriptionTypeCreateData struct {
	Type string `json:"type"`
	Attributes SubscriptionTypeCreateDataAttributes `json:"attributes"`
}

type _SubscriptionTypeCreateData SubscriptionTypeCreateData

// NewSubscriptionTypeCreateData instantiates a new SubscriptionTypeCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeCreateData(type_ string, attributes SubscriptionTypeCreateDataAttributes) *SubscriptionTypeCreateData {
	this := SubscriptionTypeCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionTypeCreateDataWithDefaults instantiates a new SubscriptionTypeCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeCreateDataWithDefaults() *SubscriptionTypeCreateData {
	this := SubscriptionTypeCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionTypeCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionTypeCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionTypeCreateData) GetAttributes() SubscriptionTypeCreateDataAttributes {
	if o == nil {
		var ret SubscriptionTypeCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeCreateData) GetAttributesOk() (*SubscriptionTypeCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionTypeCreateData) SetAttributes(v SubscriptionTypeCreateDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionTypeCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionTypeCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeCreateData := _SubscriptionTypeCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeCreateData)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeCreateData(varSubscriptionTypeCreateData)

	return err
}

type NullableSubscriptionTypeCreateData struct {
	value *SubscriptionTypeCreateData
	isSet bool
}

func (v NullableSubscriptionTypeCreateData) Get() *SubscriptionTypeCreateData {
	return v.value
}

func (v *NullableSubscriptionTypeCreateData) Set(val *SubscriptionTypeCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeCreateData(val *SubscriptionTypeCreateData) *NullableSubscriptionTypeCreateData {
	return &NullableSubscriptionTypeCreateData{value: val, isSet: true}
}

func (v NullableSubscriptionTypeCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


