/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingSchedule{}

// BillingSchedule struct for BillingSchedule
type BillingSchedule struct {
	Data BillingScheduleData `json:"data"`
}

type _BillingSchedule BillingSchedule

// NewBillingSchedule instantiates a new BillingSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingSchedule(data BillingScheduleData) *BillingSchedule {
	this := BillingSchedule{}
	this.Data = data
	return &this
}

// NewBillingScheduleWithDefaults instantiates a new BillingSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingScheduleWithDefaults() *BillingSchedule {
	this := BillingSchedule{}
	return &this
}

// GetData returns the Data field value
func (o *BillingSchedule) GetData() BillingScheduleData {
	if o == nil {
		var ret BillingScheduleData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BillingSchedule) GetDataOk() (*BillingScheduleData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BillingSchedule) SetData(v BillingScheduleData) {
	o.Data = v
}

func (o BillingSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BillingSchedule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingSchedule := _BillingSchedule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingSchedule)

	if err != nil {
		return err
	}

	*o = BillingSchedule(varBillingSchedule)

	return err
}

type NullableBillingSchedule struct {
	value *BillingSchedule
	isSet bool
}

func (v NullableBillingSchedule) Get() *BillingSchedule {
	return v.value
}

func (v *NullableBillingSchedule) Set(val *BillingSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingSchedule(val *BillingSchedule) *NullableBillingSchedule {
	return &NullableBillingSchedule{value: val, isSet: true}
}

func (v NullableBillingSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


