/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentMethodData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodData{}

// PaymentMethodData struct for PaymentMethodData
type PaymentMethodData struct {
	// payment method ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes PaymentMethodDataAttributes `json:"attributes"`
}

type _PaymentMethodData PaymentMethodData

// NewPaymentMethodData instantiates a new PaymentMethodData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodData(id string, type_ string, attributes PaymentMethodDataAttributes) *PaymentMethodData {
	this := PaymentMethodData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewPaymentMethodDataWithDefaults instantiates a new PaymentMethodData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodDataWithDefaults() *PaymentMethodData {
	this := PaymentMethodData{}
	return &this
}

// GetId returns the Id field value
func (o *PaymentMethodData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PaymentMethodData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PaymentMethodData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PaymentMethodData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *PaymentMethodData) GetAttributes() PaymentMethodDataAttributes {
	if o == nil {
		var ret PaymentMethodDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodData) GetAttributesOk() (*PaymentMethodDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PaymentMethodData) SetAttributes(v PaymentMethodDataAttributes) {
	o.Attributes = v
}

func (o PaymentMethodData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *PaymentMethodData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentMethodData := _PaymentMethodData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentMethodData)

	if err != nil {
		return err
	}

	*o = PaymentMethodData(varPaymentMethodData)

	return err
}

type NullablePaymentMethodData struct {
	value *PaymentMethodData
	isSet bool
}

func (v NullablePaymentMethodData) Get() *PaymentMethodData {
	return v.value
}

func (v *NullablePaymentMethodData) Set(val *PaymentMethodData) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodData) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodData(val *PaymentMethodData) *NullablePaymentMethodData {
	return &NullablePaymentMethodData{value: val, isSet: true}
}

func (v NullablePaymentMethodData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


