/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeUpdateData{}

// SubscriptionTypeUpdateData struct for SubscriptionTypeUpdateData
type SubscriptionTypeUpdateData struct {
	Type string `json:"type"`
	Attributes SubscriptionTypeUpdateDataAttributes `json:"attributes"`
}

type _SubscriptionTypeUpdateData SubscriptionTypeUpdateData

// NewSubscriptionTypeUpdateData instantiates a new SubscriptionTypeUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeUpdateData(type_ string, attributes SubscriptionTypeUpdateDataAttributes) *SubscriptionTypeUpdateData {
	this := SubscriptionTypeUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionTypeUpdateDataWithDefaults instantiates a new SubscriptionTypeUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeUpdateDataWithDefaults() *SubscriptionTypeUpdateData {
	this := SubscriptionTypeUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionTypeUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionTypeUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionTypeUpdateData) GetAttributes() SubscriptionTypeUpdateDataAttributes {
	if o == nil {
		var ret SubscriptionTypeUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeUpdateData) GetAttributesOk() (*SubscriptionTypeUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionTypeUpdateData) SetAttributes(v SubscriptionTypeUpdateDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionTypeUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionTypeUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeUpdateData := _SubscriptionTypeUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeUpdateData)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeUpdateData(varSubscriptionTypeUpdateData)

	return err
}

type NullableSubscriptionTypeUpdateData struct {
	value *SubscriptionTypeUpdateData
	isSet bool
}

func (v NullableSubscriptionTypeUpdateData) Get() *SubscriptionTypeUpdateData {
	return v.value
}

func (v *NullableSubscriptionTypeUpdateData) Set(val *SubscriptionTypeUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeUpdateData(val *SubscriptionTypeUpdateData) *NullableSubscriptionTypeUpdateData {
	return &NullableSubscriptionTypeUpdateData{value: val, isSet: true}
}

func (v NullableSubscriptionTypeUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


