/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the SubscriptionTypeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeUpdateDataAttributes{}

// SubscriptionTypeUpdateDataAttributes struct for SubscriptionTypeUpdateDataAttributes
type SubscriptionTypeUpdateDataAttributes struct {
	// Name
	Name *string `json:"name,omitempty"`
}

// NewSubscriptionTypeUpdateDataAttributes instantiates a new SubscriptionTypeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeUpdateDataAttributes() *SubscriptionTypeUpdateDataAttributes {
	this := SubscriptionTypeUpdateDataAttributes{}
	return &this
}

// NewSubscriptionTypeUpdateDataAttributesWithDefaults instantiates a new SubscriptionTypeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeUpdateDataAttributesWithDefaults() *SubscriptionTypeUpdateDataAttributes {
	this := SubscriptionTypeUpdateDataAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubscriptionTypeUpdateDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubscriptionTypeUpdateDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubscriptionTypeUpdateDataAttributes) SetName(v string) {
	o.Name = &v
}

func (o SubscriptionTypeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSubscriptionTypeUpdateDataAttributes struct {
	value *SubscriptionTypeUpdateDataAttributes
	isSet bool
}

func (v NullableSubscriptionTypeUpdateDataAttributes) Get() *SubscriptionTypeUpdateDataAttributes {
	return v.value
}

func (v *NullableSubscriptionTypeUpdateDataAttributes) Set(val *SubscriptionTypeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeUpdateDataAttributes(val *SubscriptionTypeUpdateDataAttributes) *NullableSubscriptionTypeUpdateDataAttributes {
	return &NullableSubscriptionTypeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableSubscriptionTypeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


