/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubType{}

// SubType struct for SubType
type SubType struct {
	Data SubTypeData `json:"data"`
}

type _SubType SubType

// NewSubType instantiates a new SubType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubType(data SubTypeData) *SubType {
	this := SubType{}
	this.Data = data
	return &this
}

// NewSubTypeWithDefaults instantiates a new SubType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeWithDefaults() *SubType {
	this := SubType{}
	return &this
}

// GetData returns the Data field value
func (o *SubType) GetData() SubTypeData {
	if o == nil {
		var ret SubTypeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubType) GetDataOk() (*SubTypeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubType) SetData(v SubTypeData) {
	o.Data = v
}

func (o SubType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubType := _SubType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubType)

	if err != nil {
		return err
	}

	*o = SubType(varSubType)

	return err
}

type NullableSubType struct {
	value *SubType
	isSet bool
}

func (v NullableSubType) Get() *SubType {
	return v.value
}

func (v *NullableSubType) Set(val *SubType) {
	v.value = val
	v.isSet = true
}

func (v NullableSubType) IsSet() bool {
	return v.isSet
}

func (v *NullableSubType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubType(val *SubType) *NullableSubType {
	return &NullableSubType{value: val, isSet: true}
}

func (v NullableSubType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


