/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentMethodsCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentMethodsCollectionDataAttributes{}

// PaymentMethodsCollectionDataAttributes struct for PaymentMethodsCollectionDataAttributes
type PaymentMethodsCollectionDataAttributes struct {
	PaymentMethods []PaymentMethodData `json:"payment_methods"`
}

type _PaymentMethodsCollectionDataAttributes PaymentMethodsCollectionDataAttributes

// NewPaymentMethodsCollectionDataAttributes instantiates a new PaymentMethodsCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentMethodsCollectionDataAttributes(paymentMethods []PaymentMethodData) *PaymentMethodsCollectionDataAttributes {
	this := PaymentMethodsCollectionDataAttributes{}
	this.PaymentMethods = paymentMethods
	return &this
}

// NewPaymentMethodsCollectionDataAttributesWithDefaults instantiates a new PaymentMethodsCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentMethodsCollectionDataAttributesWithDefaults() *PaymentMethodsCollectionDataAttributes {
	this := PaymentMethodsCollectionDataAttributes{}
	return &this
}

// GetPaymentMethods returns the PaymentMethods field value
func (o *PaymentMethodsCollectionDataAttributes) GetPaymentMethods() []PaymentMethodData {
	if o == nil {
		var ret []PaymentMethodData
		return ret
	}

	return o.PaymentMethods
}

// GetPaymentMethodsOk returns a tuple with the PaymentMethods field value
// and a boolean to check if the value has been set.
func (o *PaymentMethodsCollectionDataAttributes) GetPaymentMethodsOk() ([]PaymentMethodData, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentMethods, true
}

// SetPaymentMethods sets field value
func (o *PaymentMethodsCollectionDataAttributes) SetPaymentMethods(v []PaymentMethodData) {
	o.PaymentMethods = v
}

func (o PaymentMethodsCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentMethodsCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["payment_methods"] = o.PaymentMethods
	return toSerialize, nil
}

func (o *PaymentMethodsCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"payment_methods",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentMethodsCollectionDataAttributes := _PaymentMethodsCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentMethodsCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = PaymentMethodsCollectionDataAttributes(varPaymentMethodsCollectionDataAttributes)

	return err
}

type NullablePaymentMethodsCollectionDataAttributes struct {
	value *PaymentMethodsCollectionDataAttributes
	isSet bool
}

func (v NullablePaymentMethodsCollectionDataAttributes) Get() *PaymentMethodsCollectionDataAttributes {
	return v.value
}

func (v *NullablePaymentMethodsCollectionDataAttributes) Set(val *PaymentMethodsCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentMethodsCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentMethodsCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentMethodsCollectionDataAttributes(val *PaymentMethodsCollectionDataAttributes) *NullablePaymentMethodsCollectionDataAttributes {
	return &NullablePaymentMethodsCollectionDataAttributes{value: val, isSet: true}
}

func (v NullablePaymentMethodsCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentMethodsCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


