/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeDataAttributes{}

// SubscriptionTypeDataAttributes struct for SubscriptionTypeDataAttributes
type SubscriptionTypeDataAttributes struct {
	// Name
	Name string `json:"name"`
	// Description
	Desc string `json:"desc"`
	// Status
	Status string `json:"status"`
	// Updated At
	UpdatedAt time.Time `json:"updated_at"`
	// Created At
	CreatedAt time.Time `json:"created_at"`
}

type _SubscriptionTypeDataAttributes SubscriptionTypeDataAttributes

// NewSubscriptionTypeDataAttributes instantiates a new SubscriptionTypeDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeDataAttributes(name string, desc string, status string, updatedAt time.Time, createdAt time.Time) *SubscriptionTypeDataAttributes {
	this := SubscriptionTypeDataAttributes{}
	this.Name = name
	this.Desc = desc
	this.Status = status
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewSubscriptionTypeDataAttributesWithDefaults instantiates a new SubscriptionTypeDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeDataAttributesWithDefaults() *SubscriptionTypeDataAttributes {
	this := SubscriptionTypeDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *SubscriptionTypeDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubscriptionTypeDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDesc returns the Desc field value
func (o *SubscriptionTypeDataAttributes) GetDesc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Desc
}

// GetDescOk returns a tuple with the Desc field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataAttributes) GetDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desc, true
}

// SetDesc sets field value
func (o *SubscriptionTypeDataAttributes) SetDesc(v string) {
	o.Desc = v
}

// GetStatus returns the Status field value
func (o *SubscriptionTypeDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SubscriptionTypeDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SubscriptionTypeDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SubscriptionTypeDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SubscriptionTypeDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SubscriptionTypeDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SubscriptionTypeDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["desc"] = o.Desc
	toSerialize["status"] = o.Status
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *SubscriptionTypeDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"desc",
		"status",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeDataAttributes := _SubscriptionTypeDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeDataAttributes)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeDataAttributes(varSubscriptionTypeDataAttributes)

	return err
}

type NullableSubscriptionTypeDataAttributes struct {
	value *SubscriptionTypeDataAttributes
	isSet bool
}

func (v NullableSubscriptionTypeDataAttributes) Get() *SubscriptionTypeDataAttributes {
	return v.value
}

func (v *NullableSubscriptionTypeDataAttributes) Set(val *SubscriptionTypeDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeDataAttributes(val *SubscriptionTypeDataAttributes) *NullableSubscriptionTypeDataAttributes {
	return &NullableSubscriptionTypeDataAttributes{value: val, isSet: true}
}

func (v NullableSubscriptionTypeDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


