/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionPlansCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPlansCollection{}

// SubscriptionPlansCollection struct for SubscriptionPlansCollection
type SubscriptionPlansCollection struct {
	Data []SubscriptionPlanData `json:"data"`
	Links LinksPagination `json:"links"`
}

type _SubscriptionPlansCollection SubscriptionPlansCollection

// NewSubscriptionPlansCollection instantiates a new SubscriptionPlansCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPlansCollection(data []SubscriptionPlanData, links LinksPagination) *SubscriptionPlansCollection {
	this := SubscriptionPlansCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewSubscriptionPlansCollectionWithDefaults instantiates a new SubscriptionPlansCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPlansCollectionWithDefaults() *SubscriptionPlansCollection {
	this := SubscriptionPlansCollection{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionPlansCollection) GetData() []SubscriptionPlanData {
	if o == nil {
		var ret []SubscriptionPlanData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlansCollection) GetDataOk() ([]SubscriptionPlanData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SubscriptionPlansCollection) SetData(v []SubscriptionPlanData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *SubscriptionPlansCollection) GetLinks() LinksPagination {
	if o == nil {
		var ret LinksPagination
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlansCollection) GetLinksOk() (*LinksPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *SubscriptionPlansCollection) SetLinks(v LinksPagination) {
	o.Links = v
}

func (o SubscriptionPlansCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPlansCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *SubscriptionPlansCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionPlansCollection := _SubscriptionPlansCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionPlansCollection)

	if err != nil {
		return err
	}

	*o = SubscriptionPlansCollection(varSubscriptionPlansCollection)

	return err
}

type NullableSubscriptionPlansCollection struct {
	value *SubscriptionPlansCollection
	isSet bool
}

func (v NullableSubscriptionPlansCollection) Get() *SubscriptionPlansCollection {
	return v.value
}

func (v *NullableSubscriptionPlansCollection) Set(val *SubscriptionPlansCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPlansCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPlansCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPlansCollection(val *SubscriptionPlansCollection) *NullableSubscriptionPlansCollection {
	return &NullableSubscriptionPlansCollection{value: val, isSet: true}
}

func (v NullableSubscriptionPlansCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPlansCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


