/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SubTypeDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypeDataAttributes{}

// SubTypeDataAttributes struct for SubTypeDataAttributes
type SubTypeDataAttributes struct {
	// Name
	Name string `json:"name"`
	// Description
	Description string `json:"description"`
	// Status
	Status string `json:"status"`
	// Updated At
	UpdatedAt time.Time `json:"updated_at"`
	// Created At
	CreatedAt time.Time `json:"created_at"`
}

type _SubTypeDataAttributes SubTypeDataAttributes

// NewSubTypeDataAttributes instantiates a new SubTypeDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypeDataAttributes(name string, description string, status string, updatedAt time.Time, createdAt time.Time) *SubTypeDataAttributes {
	this := SubTypeDataAttributes{}
	this.Name = name
	this.Description = description
	this.Status = status
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewSubTypeDataAttributesWithDefaults instantiates a new SubTypeDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeDataAttributesWithDefaults() *SubTypeDataAttributes {
	this := SubTypeDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *SubTypeDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubTypeDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubTypeDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SubTypeDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SubTypeDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SubTypeDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetStatus returns the Status field value
func (o *SubTypeDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubTypeDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SubTypeDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SubTypeDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SubTypeDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SubTypeDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SubTypeDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SubTypeDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SubTypeDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o SubTypeDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypeDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["status"] = o.Status
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *SubTypeDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"status",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubTypeDataAttributes := _SubTypeDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubTypeDataAttributes)

	if err != nil {
		return err
	}

	*o = SubTypeDataAttributes(varSubTypeDataAttributes)

	return err
}

type NullableSubTypeDataAttributes struct {
	value *SubTypeDataAttributes
	isSet bool
}

func (v NullableSubTypeDataAttributes) Get() *SubTypeDataAttributes {
	return v.value
}

func (v *NullableSubTypeDataAttributes) Set(val *SubTypeDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypeDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypeDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypeDataAttributes(val *SubTypeDataAttributes) *NullableSubTypeDataAttributes {
	return &NullableSubTypeDataAttributes{value: val, isSet: true}
}

func (v NullableSubTypeDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypeDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


