/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RelationshipsDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipsDataInner{}

// RelationshipsDataInner struct for RelationshipsDataInner
type RelationshipsDataInner struct {
	Id string `json:"id"`
	Type string `json:"type"`
}

type _RelationshipsDataInner RelationshipsDataInner

// NewRelationshipsDataInner instantiates a new RelationshipsDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipsDataInner(id string, type_ string) *RelationshipsDataInner {
	this := RelationshipsDataInner{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewRelationshipsDataInnerWithDefaults instantiates a new RelationshipsDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipsDataInnerWithDefaults() *RelationshipsDataInner {
	this := RelationshipsDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *RelationshipsDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RelationshipsDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RelationshipsDataInner) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RelationshipsDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RelationshipsDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RelationshipsDataInner) SetType(v string) {
	o.Type = v
}

func (o RelationshipsDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipsDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *RelationshipsDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationshipsDataInner := _RelationshipsDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRelationshipsDataInner)

	if err != nil {
		return err
	}

	*o = RelationshipsDataInner(varRelationshipsDataInner)

	return err
}

type NullableRelationshipsDataInner struct {
	value *RelationshipsDataInner
	isSet bool
}

func (v NullableRelationshipsDataInner) Get() *RelationshipsDataInner {
	return v.value
}

func (v *NullableRelationshipsDataInner) Set(val *RelationshipsDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipsDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipsDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipsDataInner(val *RelationshipsDataInner) *NullableRelationshipsDataInner {
	return &NullableRelationshipsDataInner{value: val, isSet: true}
}

func (v NullableRelationshipsDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipsDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


