/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypesCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypesCollectionData{}

// SubscriptionTypesCollectionData struct for SubscriptionTypesCollectionData
type SubscriptionTypesCollectionData struct {
	Type string `json:"type"`
	Attributes SubscriptionTypesCollectionDataAttributes `json:"attributes"`
}

type _SubscriptionTypesCollectionData SubscriptionTypesCollectionData

// NewSubscriptionTypesCollectionData instantiates a new SubscriptionTypesCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypesCollectionData(type_ string, attributes SubscriptionTypesCollectionDataAttributes) *SubscriptionTypesCollectionData {
	this := SubscriptionTypesCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionTypesCollectionDataWithDefaults instantiates a new SubscriptionTypesCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypesCollectionDataWithDefaults() *SubscriptionTypesCollectionData {
	this := SubscriptionTypesCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionTypesCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypesCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionTypesCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionTypesCollectionData) GetAttributes() SubscriptionTypesCollectionDataAttributes {
	if o == nil {
		var ret SubscriptionTypesCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypesCollectionData) GetAttributesOk() (*SubscriptionTypesCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionTypesCollectionData) SetAttributes(v SubscriptionTypesCollectionDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionTypesCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypesCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionTypesCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypesCollectionData := _SubscriptionTypesCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypesCollectionData)

	if err != nil {
		return err
	}

	*o = SubscriptionTypesCollectionData(varSubscriptionTypesCollectionData)

	return err
}

type NullableSubscriptionTypesCollectionData struct {
	value *SubscriptionTypesCollectionData
	isSet bool
}

func (v NullableSubscriptionTypesCollectionData) Get() *SubscriptionTypesCollectionData {
	return v.value
}

func (v *NullableSubscriptionTypesCollectionData) Set(val *SubscriptionTypesCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypesCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypesCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypesCollectionData(val *SubscriptionTypesCollectionData) *NullableSubscriptionTypesCollectionData {
	return &NullableSubscriptionTypesCollectionData{value: val, isSet: true}
}

func (v NullableSubscriptionTypesCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypesCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


