/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the SubscriptionUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionUpdateDataAttributes{}

// SubscriptionUpdateDataAttributes struct for SubscriptionUpdateDataAttributes
type SubscriptionUpdateDataAttributes struct {
	// Plan ID object ID
	PlanId *string `json:"plan_id,omitempty"`
	// Status
	Status *string `json:"status,omitempty"`
	// Payment Method ID
	PaymentMethodId *string `json:"payment_method_id,omitempty"`
}

// NewSubscriptionUpdateDataAttributes instantiates a new SubscriptionUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionUpdateDataAttributes() *SubscriptionUpdateDataAttributes {
	this := SubscriptionUpdateDataAttributes{}
	return &this
}

// NewSubscriptionUpdateDataAttributesWithDefaults instantiates a new SubscriptionUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionUpdateDataAttributesWithDefaults() *SubscriptionUpdateDataAttributes {
	this := SubscriptionUpdateDataAttributes{}
	return &this
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *SubscriptionUpdateDataAttributes) GetPlanId() string {
	if o == nil || IsNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionUpdateDataAttributes) GetPlanIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *SubscriptionUpdateDataAttributes) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *SubscriptionUpdateDataAttributes) SetPlanId(v string) {
	o.PlanId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubscriptionUpdateDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubscriptionUpdateDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubscriptionUpdateDataAttributes) SetStatus(v string) {
	o.Status = &v
}

// GetPaymentMethodId returns the PaymentMethodId field value if set, zero value otherwise.
func (o *SubscriptionUpdateDataAttributes) GetPaymentMethodId() string {
	if o == nil || IsNil(o.PaymentMethodId) {
		var ret string
		return ret
	}
	return *o.PaymentMethodId
}

// GetPaymentMethodIdOk returns a tuple with the PaymentMethodId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionUpdateDataAttributes) GetPaymentMethodIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentMethodId) {
		return nil, false
	}
	return o.PaymentMethodId, true
}

// HasPaymentMethodId returns a boolean if a field has been set.
func (o *SubscriptionUpdateDataAttributes) HasPaymentMethodId() bool {
	if o != nil && !IsNil(o.PaymentMethodId) {
		return true
	}

	return false
}

// SetPaymentMethodId gets a reference to the given string and assigns it to the PaymentMethodId field.
func (o *SubscriptionUpdateDataAttributes) SetPaymentMethodId(v string) {
	o.PaymentMethodId = &v
}

func (o SubscriptionUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PlanId) {
		toSerialize["plan_id"] = o.PlanId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PaymentMethodId) {
		toSerialize["payment_method_id"] = o.PaymentMethodId
	}
	return toSerialize, nil
}

type NullableSubscriptionUpdateDataAttributes struct {
	value *SubscriptionUpdateDataAttributes
	isSet bool
}

func (v NullableSubscriptionUpdateDataAttributes) Get() *SubscriptionUpdateDataAttributes {
	return v.value
}

func (v *NullableSubscriptionUpdateDataAttributes) Set(val *SubscriptionUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionUpdateDataAttributes(val *SubscriptionUpdateDataAttributes) *NullableSubscriptionUpdateDataAttributes {
	return &NullableSubscriptionUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableSubscriptionUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


