/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubTypeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypeUpdate{}

// SubTypeUpdate struct for SubTypeUpdate
type SubTypeUpdate struct {
	Data SubTypeUpdateData `json:"data"`
}

type _SubTypeUpdate SubTypeUpdate

// NewSubTypeUpdate instantiates a new SubTypeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypeUpdate(data SubTypeUpdateData) *SubTypeUpdate {
	this := SubTypeUpdate{}
	this.Data = data
	return &this
}

// NewSubTypeUpdateWithDefaults instantiates a new SubTypeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeUpdateWithDefaults() *SubTypeUpdate {
	this := SubTypeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubTypeUpdate) GetData() SubTypeUpdateData {
	if o == nil {
		var ret SubTypeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubTypeUpdate) GetDataOk() (*SubTypeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubTypeUpdate) SetData(v SubTypeUpdateData) {
	o.Data = v
}

func (o SubTypeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubTypeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubTypeUpdate := _SubTypeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubTypeUpdate)

	if err != nil {
		return err
	}

	*o = SubTypeUpdate(varSubTypeUpdate)

	return err
}

type NullableSubTypeUpdate struct {
	value *SubTypeUpdate
	isSet bool
}

func (v NullableSubTypeUpdate) Get() *SubTypeUpdate {
	return v.value
}

func (v *NullableSubTypeUpdate) Set(val *SubTypeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypeUpdate(val *SubTypeUpdate) *NullableSubTypeUpdate {
	return &NullableSubTypeUpdate{value: val, isSet: true}
}

func (v NullableSubTypeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


