/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionType{}

// SubscriptionType struct for SubscriptionType
type SubscriptionType struct {
	Data SubscriptionTypeData `json:"data"`
	Included []SubscriptionPlanData `json:"included"`
}

type _SubscriptionType SubscriptionType

// NewSubscriptionType instantiates a new SubscriptionType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionType(data SubscriptionTypeData, included []SubscriptionPlanData) *SubscriptionType {
	this := SubscriptionType{}
	this.Data = data
	this.Included = included
	return &this
}

// NewSubscriptionTypeWithDefaults instantiates a new SubscriptionType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeWithDefaults() *SubscriptionType {
	this := SubscriptionType{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionType) GetData() SubscriptionTypeData {
	if o == nil {
		var ret SubscriptionTypeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionType) GetDataOk() (*SubscriptionTypeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionType) SetData(v SubscriptionTypeData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *SubscriptionType) GetIncluded() []SubscriptionPlanData {
	if o == nil {
		var ret []SubscriptionPlanData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *SubscriptionType) GetIncludedOk() ([]SubscriptionPlanData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *SubscriptionType) SetIncluded(v []SubscriptionPlanData) {
	o.Included = v
}

func (o SubscriptionType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *SubscriptionType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionType := _SubscriptionType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionType)

	if err != nil {
		return err
	}

	*o = SubscriptionType(varSubscriptionType)

	return err
}

type NullableSubscriptionType struct {
	value *SubscriptionType
	isSet bool
}

func (v NullableSubscriptionType) Get() *SubscriptionType {
	return v.value
}

func (v *NullableSubscriptionType) Set(val *SubscriptionType) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionType) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionType(val *SubscriptionType) *NullableSubscriptionType {
	return &NullableSubscriptionType{value: val, isSet: true}
}

func (v NullableSubscriptionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


