/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubPlanData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubPlanData{}

// SubPlanData struct for SubPlanData
type SubPlanData struct {
	// Subscription Plan ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SubPlanDataAttributes `json:"attributes"`
}

type _SubPlanData SubPlanData

// NewSubPlanData instantiates a new SubPlanData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubPlanData(id string, type_ string, attributes SubPlanDataAttributes) *SubPlanData {
	this := SubPlanData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubPlanDataWithDefaults instantiates a new SubPlanData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubPlanDataWithDefaults() *SubPlanData {
	this := SubPlanData{}
	return &this
}

// GetId returns the Id field value
func (o *SubPlanData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubPlanData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubPlanData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SubPlanData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubPlanData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubPlanData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubPlanData) GetAttributes() SubPlanDataAttributes {
	if o == nil {
		var ret SubPlanDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubPlanData) GetAttributesOk() (*SubPlanDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubPlanData) SetAttributes(v SubPlanDataAttributes) {
	o.Attributes = v
}

func (o SubPlanData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubPlanData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubPlanData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubPlanData := _SubPlanData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubPlanData)

	if err != nil {
		return err
	}

	*o = SubPlanData(varSubPlanData)

	return err
}

type NullableSubPlanData struct {
	value *SubPlanData
	isSet bool
}

func (v NullableSubPlanData) Get() *SubPlanData {
	return v.value
}

func (v *NullableSubPlanData) Set(val *SubPlanData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubPlanData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubPlanData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubPlanData(val *SubPlanData) *NullableSubPlanData {
	return &NullableSubPlanData{value: val, isSet: true}
}

func (v NullableSubPlanData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubPlanData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


