/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RelationshipsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationshipsData{}

// RelationshipsData struct for RelationshipsData
type RelationshipsData struct {
	Id string `json:"id"`
	Type string `json:"type"`
}

type _RelationshipsData RelationshipsData

// NewRelationshipsData instantiates a new RelationshipsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationshipsData(id string, type_ string) *RelationshipsData {
	this := RelationshipsData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewRelationshipsDataWithDefaults instantiates a new RelationshipsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipsDataWithDefaults() *RelationshipsData {
	this := RelationshipsData{}
	return &this
}

// GetId returns the Id field value
func (o *RelationshipsData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RelationshipsData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RelationshipsData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RelationshipsData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RelationshipsData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RelationshipsData) SetType(v string) {
	o.Type = v
}

func (o RelationshipsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationshipsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *RelationshipsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationshipsData := _RelationshipsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRelationshipsData)

	if err != nil {
		return err
	}

	*o = RelationshipsData(varRelationshipsData)

	return err
}

type NullableRelationshipsData struct {
	value *RelationshipsData
	isSet bool
}

func (v NullableRelationshipsData) Get() *RelationshipsData {
	return v.value
}

func (v *NullableRelationshipsData) Set(val *RelationshipsData) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipsData) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipsData(val *RelationshipsData) *NullableRelationshipsData {
	return &NullableRelationshipsData{value: val, isSet: true}
}

func (v NullableRelationshipsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


