/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriberUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriberUpdate{}

// SubscriberUpdate struct for SubscriberUpdate
type SubscriberUpdate struct {
	Data SubscriberUpdateData `json:"data"`
}

type _SubscriberUpdate SubscriberUpdate

// NewSubscriberUpdate instantiates a new SubscriberUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriberUpdate(data SubscriberUpdateData) *SubscriberUpdate {
	this := SubscriberUpdate{}
	this.Data = data
	return &this
}

// NewSubscriberUpdateWithDefaults instantiates a new SubscriberUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriberUpdateWithDefaults() *SubscriberUpdate {
	this := SubscriberUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriberUpdate) GetData() SubscriberUpdateData {
	if o == nil {
		var ret SubscriberUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriberUpdate) GetDataOk() (*SubscriberUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriberUpdate) SetData(v SubscriberUpdateData) {
	o.Data = v
}

func (o SubscriberUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriberUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriberUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriberUpdate := _SubscriberUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriberUpdate)

	if err != nil {
		return err
	}

	*o = SubscriberUpdate(varSubscriberUpdate)

	return err
}

type NullableSubscriberUpdate struct {
	value *SubscriberUpdate
	isSet bool
}

func (v NullableSubscriberUpdate) Get() *SubscriberUpdate {
	return v.value
}

func (v *NullableSubscriberUpdate) Set(val *SubscriberUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriberUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriberUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriberUpdate(val *SubscriberUpdate) *NullableSubscriberUpdate {
	return &NullableSubscriberUpdate{value: val, isSet: true}
}

func (v NullableSubscriberUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriberUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


