/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionCreate{}

// SubscriptionCreate struct for SubscriptionCreate
type SubscriptionCreate struct {
	Data SubscriptionCreateData `json:"data"`
}

type _SubscriptionCreate SubscriptionCreate

// NewSubscriptionCreate instantiates a new SubscriptionCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionCreate(data SubscriptionCreateData) *SubscriptionCreate {
	this := SubscriptionCreate{}
	this.Data = data
	return &this
}

// NewSubscriptionCreateWithDefaults instantiates a new SubscriptionCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionCreateWithDefaults() *SubscriptionCreate {
	this := SubscriptionCreate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionCreate) GetData() SubscriptionCreateData {
	if o == nil {
		var ret SubscriptionCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreate) GetDataOk() (*SubscriptionCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionCreate) SetData(v SubscriptionCreateData) {
	o.Data = v
}

func (o SubscriptionCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionCreate := _SubscriptionCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionCreate)

	if err != nil {
		return err
	}

	*o = SubscriptionCreate(varSubscriptionCreate)

	return err
}

type NullableSubscriptionCreate struct {
	value *SubscriptionCreate
	isSet bool
}

func (v NullableSubscriptionCreate) Get() *SubscriptionCreate {
	return v.value
}

func (v *NullableSubscriptionCreate) Set(val *SubscriptionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionCreate(val *SubscriptionCreate) *NullableSubscriptionCreate {
	return &NullableSubscriptionCreate{value: val, isSet: true}
}

func (v NullableSubscriptionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


