/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriberUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriberUpdateData{}

// SubscriberUpdateData struct for SubscriberUpdateData
type SubscriberUpdateData struct {
	Type string `json:"type"`
	Attributes SubscriberUpdateDataAttributes `json:"attributes"`
}

type _SubscriberUpdateData SubscriberUpdateData

// NewSubscriberUpdateData instantiates a new SubscriberUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriberUpdateData(type_ string, attributes SubscriberUpdateDataAttributes) *SubscriberUpdateData {
	this := SubscriberUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriberUpdateDataWithDefaults instantiates a new SubscriberUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriberUpdateDataWithDefaults() *SubscriberUpdateData {
	this := SubscriberUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriberUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriberUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriberUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriberUpdateData) GetAttributes() SubscriberUpdateDataAttributes {
	if o == nil {
		var ret SubscriberUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriberUpdateData) GetAttributesOk() (*SubscriberUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriberUpdateData) SetAttributes(v SubscriberUpdateDataAttributes) {
	o.Attributes = v
}

func (o SubscriberUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriberUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriberUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriberUpdateData := _SubscriberUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriberUpdateData)

	if err != nil {
		return err
	}

	*o = SubscriberUpdateData(varSubscriberUpdateData)

	return err
}

type NullableSubscriberUpdateData struct {
	value *SubscriberUpdateData
	isSet bool
}

func (v NullableSubscriberUpdateData) Get() *SubscriberUpdateData {
	return v.value
}

func (v *NullableSubscriberUpdateData) Set(val *SubscriberUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriberUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriberUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriberUpdateData(val *SubscriberUpdateData) *NullableSubscriberUpdateData {
	return &NullableSubscriberUpdateData{value: val, isSet: true}
}

func (v NullableSubscriberUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriberUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


