/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeDataRelationshipsSubscriptionPlanRelation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeDataRelationshipsSubscriptionPlanRelation{}

// SubscriptionTypeDataRelationshipsSubscriptionPlanRelation struct for SubscriptionTypeDataRelationshipsSubscriptionPlanRelation
type SubscriptionTypeDataRelationshipsSubscriptionPlanRelation struct {
	Data []Relationships `json:"data"`
}

type _SubscriptionTypeDataRelationshipsSubscriptionPlanRelation SubscriptionTypeDataRelationshipsSubscriptionPlanRelation

// NewSubscriptionTypeDataRelationshipsSubscriptionPlanRelation instantiates a new SubscriptionTypeDataRelationshipsSubscriptionPlanRelation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeDataRelationshipsSubscriptionPlanRelation(data []Relationships) *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation {
	this := SubscriptionTypeDataRelationshipsSubscriptionPlanRelation{}
	this.Data = data
	return &this
}

// NewSubscriptionTypeDataRelationshipsSubscriptionPlanRelationWithDefaults instantiates a new SubscriptionTypeDataRelationshipsSubscriptionPlanRelation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeDataRelationshipsSubscriptionPlanRelationWithDefaults() *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation {
	this := SubscriptionTypeDataRelationshipsSubscriptionPlanRelation{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) GetData() []Relationships {
	if o == nil {
		var ret []Relationships
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) GetDataOk() ([]Relationships, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) SetData(v []Relationships) {
	o.Data = v
}

func (o SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeDataRelationshipsSubscriptionPlanRelation := _SubscriptionTypeDataRelationshipsSubscriptionPlanRelation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeDataRelationshipsSubscriptionPlanRelation)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeDataRelationshipsSubscriptionPlanRelation(varSubscriptionTypeDataRelationshipsSubscriptionPlanRelation)

	return err
}

type NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation struct {
	value *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation
	isSet bool
}

func (v NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) Get() *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation {
	return v.value
}

func (v *NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) Set(val *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation(val *SubscriptionTypeDataRelationshipsSubscriptionPlanRelation) *NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation {
	return &NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation{value: val, isSet: true}
}

func (v NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeDataRelationshipsSubscriptionPlanRelation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


