/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeData{}

// SubscriptionTypeData struct for SubscriptionTypeData
type SubscriptionTypeData struct {
	// Subscription type ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SubscriptionTypeDataAttributes `json:"attributes"`
}

type _SubscriptionTypeData SubscriptionTypeData

// NewSubscriptionTypeData instantiates a new SubscriptionTypeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeData(id string, type_ string, attributes SubscriptionTypeDataAttributes) *SubscriptionTypeData {
	this := SubscriptionTypeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionTypeDataWithDefaults instantiates a new SubscriptionTypeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeDataWithDefaults() *SubscriptionTypeData {
	this := SubscriptionTypeData{}
	return &this
}

// GetId returns the Id field value
func (o *SubscriptionTypeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubscriptionTypeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SubscriptionTypeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionTypeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionTypeData) GetAttributes() SubscriptionTypeDataAttributes {
	if o == nil {
		var ret SubscriptionTypeDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeData) GetAttributesOk() (*SubscriptionTypeDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionTypeData) SetAttributes(v SubscriptionTypeDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionTypeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionTypeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeData := _SubscriptionTypeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeData)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeData(varSubscriptionTypeData)

	return err
}

type NullableSubscriptionTypeData struct {
	value *SubscriptionTypeData
	isSet bool
}

func (v NullableSubscriptionTypeData) Get() *SubscriptionTypeData {
	return v.value
}

func (v *NullableSubscriptionTypeData) Set(val *SubscriptionTypeData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeData(val *SubscriptionTypeData) *NullableSubscriptionTypeData {
	return &NullableSubscriptionTypeData{value: val, isSet: true}
}

func (v NullableSubscriptionTypeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


