/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingSchedulesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingSchedulesCollection{}

// BillingSchedulesCollection struct for BillingSchedulesCollection
type BillingSchedulesCollection struct {
	Data []BillingSchedulesCollectionDataInner `json:"data"`
	Links LinksPagination `json:"links"`
}

type _BillingSchedulesCollection BillingSchedulesCollection

// NewBillingSchedulesCollection instantiates a new BillingSchedulesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingSchedulesCollection(data []BillingSchedulesCollectionDataInner, links LinksPagination) *BillingSchedulesCollection {
	this := BillingSchedulesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewBillingSchedulesCollectionWithDefaults instantiates a new BillingSchedulesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingSchedulesCollectionWithDefaults() *BillingSchedulesCollection {
	this := BillingSchedulesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *BillingSchedulesCollection) GetData() []BillingSchedulesCollectionDataInner {
	if o == nil {
		var ret []BillingSchedulesCollectionDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollection) GetDataOk() ([]BillingSchedulesCollectionDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BillingSchedulesCollection) SetData(v []BillingSchedulesCollectionDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *BillingSchedulesCollection) GetLinks() LinksPagination {
	if o == nil {
		var ret LinksPagination
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollection) GetLinksOk() (*LinksPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BillingSchedulesCollection) SetLinks(v LinksPagination) {
	o.Links = v
}

func (o BillingSchedulesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingSchedulesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *BillingSchedulesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingSchedulesCollection := _BillingSchedulesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingSchedulesCollection)

	if err != nil {
		return err
	}

	*o = BillingSchedulesCollection(varBillingSchedulesCollection)

	return err
}

type NullableBillingSchedulesCollection struct {
	value *BillingSchedulesCollection
	isSet bool
}

func (v NullableBillingSchedulesCollection) Get() *BillingSchedulesCollection {
	return v.value
}

func (v *NullableBillingSchedulesCollection) Set(val *BillingSchedulesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingSchedulesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingSchedulesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingSchedulesCollection(val *BillingSchedulesCollection) *NullableBillingSchedulesCollection {
	return &NullableBillingSchedulesCollection{value: val, isSet: true}
}

func (v NullableBillingSchedulesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingSchedulesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


