/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriberData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriberData{}

// SubscriberData struct for SubscriberData
type SubscriberData struct {
	// Subscriber ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SubscriberDataAttributes `json:"attributes"`
}

type _SubscriberData SubscriberData

// NewSubscriberData instantiates a new SubscriberData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriberData(id string, type_ string, attributes SubscriberDataAttributes) *SubscriberData {
	this := SubscriberData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriberDataWithDefaults instantiates a new SubscriberData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriberDataWithDefaults() *SubscriberData {
	this := SubscriberData{}
	return &this
}

// GetId returns the Id field value
func (o *SubscriberData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubscriberData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubscriberData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SubscriberData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriberData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriberData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriberData) GetAttributes() SubscriberDataAttributes {
	if o == nil {
		var ret SubscriberDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriberData) GetAttributesOk() (*SubscriberDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriberData) SetAttributes(v SubscriberDataAttributes) {
	o.Attributes = v
}

func (o SubscriberData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriberData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriberData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriberData := _SubscriberData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriberData)

	if err != nil {
		return err
	}

	*o = SubscriberData(varSubscriberData)

	return err
}

type NullableSubscriberData struct {
	value *SubscriberData
	isSet bool
}

func (v NullableSubscriberData) Get() *SubscriberData {
	return v.value
}

func (v *NullableSubscriberData) Set(val *SubscriberData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriberData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriberData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriberData(val *SubscriberData) *NullableSubscriberData {
	return &NullableSubscriberData{value: val, isSet: true}
}

func (v NullableSubscriberData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriberData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


