/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionCreateData{}

// SubscriptionCreateData struct for SubscriptionCreateData
type SubscriptionCreateData struct {
	Type string `json:"type"`
	Attributes SubscriptionCreateDataAttributes `json:"attributes"`
}

type _SubscriptionCreateData SubscriptionCreateData

// NewSubscriptionCreateData instantiates a new SubscriptionCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionCreateData(type_ string, attributes SubscriptionCreateDataAttributes) *SubscriptionCreateData {
	this := SubscriptionCreateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionCreateDataWithDefaults instantiates a new SubscriptionCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionCreateDataWithDefaults() *SubscriptionCreateData {
	this := SubscriptionCreateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionCreateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionCreateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionCreateData) GetAttributes() SubscriptionCreateDataAttributes {
	if o == nil {
		var ret SubscriptionCreateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionCreateData) GetAttributesOk() (*SubscriptionCreateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionCreateData) SetAttributes(v SubscriptionCreateDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionCreateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionCreateData := _SubscriptionCreateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionCreateData)

	if err != nil {
		return err
	}

	*o = SubscriptionCreateData(varSubscriptionCreateData)

	return err
}

type NullableSubscriptionCreateData struct {
	value *SubscriptionCreateData
	isSet bool
}

func (v NullableSubscriptionCreateData) Get() *SubscriptionCreateData {
	return v.value
}

func (v *NullableSubscriptionCreateData) Set(val *SubscriptionCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionCreateData(val *SubscriptionCreateData) *NullableSubscriptionCreateData {
	return &NullableSubscriptionCreateData{value: val, isSet: true}
}

func (v NullableSubscriptionCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


