/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubTypeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypeData{}

// SubTypeData struct for SubTypeData
type SubTypeData struct {
	// Subscription type ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes SubTypeDataAttributes `json:"attributes"`
}

type _SubTypeData SubTypeData

// NewSubTypeData instantiates a new SubTypeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypeData(id string, type_ string, attributes SubTypeDataAttributes) *SubTypeData {
	this := SubTypeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubTypeDataWithDefaults instantiates a new SubTypeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeDataWithDefaults() *SubTypeData {
	this := SubTypeData{}
	return &this
}

// GetId returns the Id field value
func (o *SubTypeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubTypeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubTypeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SubTypeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubTypeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubTypeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubTypeData) GetAttributes() SubTypeDataAttributes {
	if o == nil {
		var ret SubTypeDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubTypeData) GetAttributesOk() (*SubTypeDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubTypeData) SetAttributes(v SubTypeDataAttributes) {
	o.Attributes = v
}

func (o SubTypeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubTypeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubTypeData := _SubTypeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubTypeData)

	if err != nil {
		return err
	}

	*o = SubTypeData(varSubTypeData)

	return err
}

type NullableSubTypeData struct {
	value *SubTypeData
	isSet bool
}

func (v NullableSubTypeData) Get() *SubTypeData {
	return v.value
}

func (v *NullableSubTypeData) Set(val *SubTypeData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypeData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypeData(val *SubTypeData) *NullableSubTypeData {
	return &NullableSubTypeData{value: val, isSet: true}
}

func (v NullableSubTypeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


