/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
)

// checks if the SubTypeUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypeUpdateDataAttributes{}

// SubTypeUpdateDataAttributes struct for SubTypeUpdateDataAttributes
type SubTypeUpdateDataAttributes struct {
	// Name
	Name *string `json:"name,omitempty"`
	// Status
	Status *string `json:"status,omitempty"`
	// Updated At
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewSubTypeUpdateDataAttributes instantiates a new SubTypeUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypeUpdateDataAttributes() *SubTypeUpdateDataAttributes {
	this := SubTypeUpdateDataAttributes{}
	return &this
}

// NewSubTypeUpdateDataAttributesWithDefaults instantiates a new SubTypeUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeUpdateDataAttributesWithDefaults() *SubTypeUpdateDataAttributes {
	this := SubTypeUpdateDataAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubTypeUpdateDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubTypeUpdateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubTypeUpdateDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubTypeUpdateDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubTypeUpdateDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubTypeUpdateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubTypeUpdateDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SubTypeUpdateDataAttributes) SetStatus(v string) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SubTypeUpdateDataAttributes) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubTypeUpdateDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SubTypeUpdateDataAttributes) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *SubTypeUpdateDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o SubTypeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypeUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableSubTypeUpdateDataAttributes struct {
	value *SubTypeUpdateDataAttributes
	isSet bool
}

func (v NullableSubTypeUpdateDataAttributes) Get() *SubTypeUpdateDataAttributes {
	return v.value
}

func (v *NullableSubTypeUpdateDataAttributes) Set(val *SubTypeUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypeUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypeUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypeUpdateDataAttributes(val *SubTypeUpdateDataAttributes) *NullableSubTypeUpdateDataAttributes {
	return &NullableSubTypeUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableSubTypeUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypeUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


