/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransactionsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionsCollection{}

// TransactionsCollection struct for TransactionsCollection
type TransactionsCollection struct {
	Data TransactionsCollectionData `json:"data"`
	Links LinksPagination `json:"links"`
}

type _TransactionsCollection TransactionsCollection

// NewTransactionsCollection instantiates a new TransactionsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionsCollection(data TransactionsCollectionData, links LinksPagination) *TransactionsCollection {
	this := TransactionsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewTransactionsCollectionWithDefaults instantiates a new TransactionsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionsCollectionWithDefaults() *TransactionsCollection {
	this := TransactionsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *TransactionsCollection) GetData() TransactionsCollectionData {
	if o == nil {
		var ret TransactionsCollectionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TransactionsCollection) GetDataOk() (*TransactionsCollectionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TransactionsCollection) SetData(v TransactionsCollectionData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *TransactionsCollection) GetLinks() LinksPagination {
	if o == nil {
		var ret LinksPagination
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *TransactionsCollection) GetLinksOk() (*LinksPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *TransactionsCollection) SetLinks(v LinksPagination) {
	o.Links = v
}

func (o TransactionsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *TransactionsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionsCollection := _TransactionsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionsCollection)

	if err != nil {
		return err
	}

	*o = TransactionsCollection(varTransactionsCollection)

	return err
}

type NullableTransactionsCollection struct {
	value *TransactionsCollection
	isSet bool
}

func (v NullableTransactionsCollection) Get() *TransactionsCollection {
	return v.value
}

func (v *NullableTransactionsCollection) Set(val *TransactionsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionsCollection(val *TransactionsCollection) *NullableTransactionsCollection {
	return &NullableTransactionsCollection{value: val, isSet: true}
}

func (v NullableTransactionsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


