/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeDepends type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeDepends{}

// SubscriptionTypeDepends struct for SubscriptionTypeDepends
type SubscriptionTypeDepends struct {
	Data []SubscriptionTypeData `json:"data"`
	Included []SubscriptionPlanData `json:"included"`
}

type _SubscriptionTypeDepends SubscriptionTypeDepends

// NewSubscriptionTypeDepends instantiates a new SubscriptionTypeDepends object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeDepends(data []SubscriptionTypeData, included []SubscriptionPlanData) *SubscriptionTypeDepends {
	this := SubscriptionTypeDepends{}
	this.Data = data
	this.Included = included
	return &this
}

// NewSubscriptionTypeDependsWithDefaults instantiates a new SubscriptionTypeDepends object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeDependsWithDefaults() *SubscriptionTypeDepends {
	this := SubscriptionTypeDepends{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionTypeDepends) GetData() []SubscriptionTypeData {
	if o == nil {
		var ret []SubscriptionTypeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDepends) GetDataOk() ([]SubscriptionTypeData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SubscriptionTypeDepends) SetData(v []SubscriptionTypeData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *SubscriptionTypeDepends) GetIncluded() []SubscriptionPlanData {
	if o == nil {
		var ret []SubscriptionPlanData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDepends) GetIncludedOk() ([]SubscriptionPlanData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *SubscriptionTypeDepends) SetIncluded(v []SubscriptionPlanData) {
	o.Included = v
}

func (o SubscriptionTypeDepends) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeDepends) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *SubscriptionTypeDepends) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeDepends := _SubscriptionTypeDepends{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeDepends)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeDepends(varSubscriptionTypeDepends)

	return err
}

type NullableSubscriptionTypeDepends struct {
	value *SubscriptionTypeDepends
	isSet bool
}

func (v NullableSubscriptionTypeDepends) Get() *SubscriptionTypeDepends {
	return v.value
}

func (v *NullableSubscriptionTypeDepends) Set(val *SubscriptionTypeDepends) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeDepends) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeDepends) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeDepends(val *SubscriptionTypeDepends) *NullableSubscriptionTypeDepends {
	return &NullableSubscriptionTypeDepends{value: val, isSet: true}
}

func (v NullableSubscriptionTypeDepends) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeDepends) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


