/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubTypesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypesCollection{}

// SubTypesCollection struct for SubTypesCollection
type SubTypesCollection struct {
	Data []SubTypeData `json:"data"`
	Links LinksPagination `json:"links"`
}

type _SubTypesCollection SubTypesCollection

// NewSubTypesCollection instantiates a new SubTypesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypesCollection(data []SubTypeData, links LinksPagination) *SubTypesCollection {
	this := SubTypesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewSubTypesCollectionWithDefaults instantiates a new SubTypesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypesCollectionWithDefaults() *SubTypesCollection {
	this := SubTypesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *SubTypesCollection) GetData() []SubTypeData {
	if o == nil {
		var ret []SubTypeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubTypesCollection) GetDataOk() ([]SubTypeData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SubTypesCollection) SetData(v []SubTypeData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *SubTypesCollection) GetLinks() LinksPagination {
	if o == nil {
		var ret LinksPagination
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *SubTypesCollection) GetLinksOk() (*LinksPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *SubTypesCollection) SetLinks(v LinksPagination) {
	o.Links = v
}

func (o SubTypesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *SubTypesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubTypesCollection := _SubTypesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubTypesCollection)

	if err != nil {
		return err
	}

	*o = SubTypesCollection(varSubTypesCollection)

	return err
}

type NullableSubTypesCollection struct {
	value *SubTypesCollection
	isSet bool
}

func (v NullableSubTypesCollection) Get() *SubTypesCollection {
	return v.value
}

func (v *NullableSubTypesCollection) Set(val *SubTypesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypesCollection(val *SubTypesCollection) *NullableSubTypesCollection {
	return &NullableSubTypesCollection{value: val, isSet: true}
}

func (v NullableSubTypesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


