/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeDataRelationships{}

// SubscriptionTypeDataRelationships struct for SubscriptionTypeDataRelationships
type SubscriptionTypeDataRelationships struct {
	SubscriptionPlanRelation Relationships `json:"subscription_plan_relation"`
}

type _SubscriptionTypeDataRelationships SubscriptionTypeDataRelationships

// NewSubscriptionTypeDataRelationships instantiates a new SubscriptionTypeDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeDataRelationships(subscriptionPlanRelation Relationships) *SubscriptionTypeDataRelationships {
	this := SubscriptionTypeDataRelationships{}
	this.SubscriptionPlanRelation = subscriptionPlanRelation
	return &this
}

// NewSubscriptionTypeDataRelationshipsWithDefaults instantiates a new SubscriptionTypeDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeDataRelationshipsWithDefaults() *SubscriptionTypeDataRelationships {
	this := SubscriptionTypeDataRelationships{}
	return &this
}

// GetSubscriptionPlanRelation returns the SubscriptionPlanRelation field value
func (o *SubscriptionTypeDataRelationships) GetSubscriptionPlanRelation() Relationships {
	if o == nil {
		var ret Relationships
		return ret
	}

	return o.SubscriptionPlanRelation
}

// GetSubscriptionPlanRelationOk returns a tuple with the SubscriptionPlanRelation field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeDataRelationships) GetSubscriptionPlanRelationOk() (*Relationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionPlanRelation, true
}

// SetSubscriptionPlanRelation sets field value
func (o *SubscriptionTypeDataRelationships) SetSubscriptionPlanRelation(v Relationships) {
	o.SubscriptionPlanRelation = v
}

func (o SubscriptionTypeDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subscription_plan_relation"] = o.SubscriptionPlanRelation
	return toSerialize, nil
}

func (o *SubscriptionTypeDataRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subscription_plan_relation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeDataRelationships := _SubscriptionTypeDataRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeDataRelationships)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeDataRelationships(varSubscriptionTypeDataRelationships)

	return err
}

type NullableSubscriptionTypeDataRelationships struct {
	value *SubscriptionTypeDataRelationships
	isSet bool
}

func (v NullableSubscriptionTypeDataRelationships) Get() *SubscriptionTypeDataRelationships {
	return v.value
}

func (v *NullableSubscriptionTypeDataRelationships) Set(val *SubscriptionTypeDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeDataRelationships(val *SubscriptionTypeDataRelationships) *NullableSubscriptionTypeDataRelationships {
	return &NullableSubscriptionTypeDataRelationships{value: val, isSet: true}
}

func (v NullableSubscriptionTypeDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


