/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingSchedulesCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingSchedulesCollectionData{}

// BillingSchedulesCollectionData struct for BillingSchedulesCollectionData
type BillingSchedulesCollectionData struct {
	Type string `json:"type"`
	Attributes BillingSchedulesCollectionDataAttributes `json:"attributes"`
}

type _BillingSchedulesCollectionData BillingSchedulesCollectionData

// NewBillingSchedulesCollectionData instantiates a new BillingSchedulesCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingSchedulesCollectionData(type_ string, attributes BillingSchedulesCollectionDataAttributes) *BillingSchedulesCollectionData {
	this := BillingSchedulesCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewBillingSchedulesCollectionDataWithDefaults instantiates a new BillingSchedulesCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingSchedulesCollectionDataWithDefaults() *BillingSchedulesCollectionData {
	this := BillingSchedulesCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *BillingSchedulesCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BillingSchedulesCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *BillingSchedulesCollectionData) GetAttributes() BillingSchedulesCollectionDataAttributes {
	if o == nil {
		var ret BillingSchedulesCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *BillingSchedulesCollectionData) GetAttributesOk() (*BillingSchedulesCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *BillingSchedulesCollectionData) SetAttributes(v BillingSchedulesCollectionDataAttributes) {
	o.Attributes = v
}

func (o BillingSchedulesCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingSchedulesCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *BillingSchedulesCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingSchedulesCollectionData := _BillingSchedulesCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingSchedulesCollectionData)

	if err != nil {
		return err
	}

	*o = BillingSchedulesCollectionData(varBillingSchedulesCollectionData)

	return err
}

type NullableBillingSchedulesCollectionData struct {
	value *BillingSchedulesCollectionData
	isSet bool
}

func (v NullableBillingSchedulesCollectionData) Get() *BillingSchedulesCollectionData {
	return v.value
}

func (v *NullableBillingSchedulesCollectionData) Set(val *BillingSchedulesCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingSchedulesCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingSchedulesCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingSchedulesCollectionData(val *BillingSchedulesCollectionData) *NullableBillingSchedulesCollectionData {
	return &NullableBillingSchedulesCollectionData{value: val, isSet: true}
}

func (v NullableBillingSchedulesCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingSchedulesCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


