/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionPlanUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPlanUpdateData{}

// SubscriptionPlanUpdateData struct for SubscriptionPlanUpdateData
type SubscriptionPlanUpdateData struct {
	Type string `json:"type"`
	Attributes SubscriptionPlanUpdateDataAttributes `json:"attributes"`
}

type _SubscriptionPlanUpdateData SubscriptionPlanUpdateData

// NewSubscriptionPlanUpdateData instantiates a new SubscriptionPlanUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPlanUpdateData(type_ string, attributes SubscriptionPlanUpdateDataAttributes) *SubscriptionPlanUpdateData {
	this := SubscriptionPlanUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionPlanUpdateDataWithDefaults instantiates a new SubscriptionPlanUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPlanUpdateDataWithDefaults() *SubscriptionPlanUpdateData {
	this := SubscriptionPlanUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionPlanUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlanUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionPlanUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionPlanUpdateData) GetAttributes() SubscriptionPlanUpdateDataAttributes {
	if o == nil {
		var ret SubscriptionPlanUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlanUpdateData) GetAttributesOk() (*SubscriptionPlanUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionPlanUpdateData) SetAttributes(v SubscriptionPlanUpdateDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionPlanUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPlanUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionPlanUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionPlanUpdateData := _SubscriptionPlanUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionPlanUpdateData)

	if err != nil {
		return err
	}

	*o = SubscriptionPlanUpdateData(varSubscriptionPlanUpdateData)

	return err
}

type NullableSubscriptionPlanUpdateData struct {
	value *SubscriptionPlanUpdateData
	isSet bool
}

func (v NullableSubscriptionPlanUpdateData) Get() *SubscriptionPlanUpdateData {
	return v.value
}

func (v *NullableSubscriptionPlanUpdateData) Set(val *SubscriptionPlanUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPlanUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPlanUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPlanUpdateData(val *SubscriptionPlanUpdateData) *NullableSubscriptionPlanUpdateData {
	return &NullableSubscriptionPlanUpdateData{value: val, isSet: true}
}

func (v NullableSubscriptionPlanUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPlanUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


