/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionPlanUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPlanUpdate{}

// SubscriptionPlanUpdate struct for SubscriptionPlanUpdate
type SubscriptionPlanUpdate struct {
	Data SubscriptionPlanUpdateData `json:"data"`
}

type _SubscriptionPlanUpdate SubscriptionPlanUpdate

// NewSubscriptionPlanUpdate instantiates a new SubscriptionPlanUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPlanUpdate(data SubscriptionPlanUpdateData) *SubscriptionPlanUpdate {
	this := SubscriptionPlanUpdate{}
	this.Data = data
	return &this
}

// NewSubscriptionPlanUpdateWithDefaults instantiates a new SubscriptionPlanUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPlanUpdateWithDefaults() *SubscriptionPlanUpdate {
	this := SubscriptionPlanUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionPlanUpdate) GetData() SubscriptionPlanUpdateData {
	if o == nil {
		var ret SubscriptionPlanUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlanUpdate) GetDataOk() (*SubscriptionPlanUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionPlanUpdate) SetData(v SubscriptionPlanUpdateData) {
	o.Data = v
}

func (o SubscriptionPlanUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPlanUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionPlanUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionPlanUpdate := _SubscriptionPlanUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionPlanUpdate)

	if err != nil {
		return err
	}

	*o = SubscriptionPlanUpdate(varSubscriptionPlanUpdate)

	return err
}

type NullableSubscriptionPlanUpdate struct {
	value *SubscriptionPlanUpdate
	isSet bool
}

func (v NullableSubscriptionPlanUpdate) Get() *SubscriptionPlanUpdate {
	return v.value
}

func (v *NullableSubscriptionPlanUpdate) Set(val *SubscriptionPlanUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPlanUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPlanUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPlanUpdate(val *SubscriptionPlanUpdate) *NullableSubscriptionPlanUpdate {
	return &NullableSubscriptionPlanUpdate{value: val, isSet: true}
}

func (v NullableSubscriptionPlanUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPlanUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


