/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeUpdate{}

// SubscriptionTypeUpdate struct for SubscriptionTypeUpdate
type SubscriptionTypeUpdate struct {
	Data SubscriptionTypeUpdateData `json:"data"`
}

type _SubscriptionTypeUpdate SubscriptionTypeUpdate

// NewSubscriptionTypeUpdate instantiates a new SubscriptionTypeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeUpdate(data SubscriptionTypeUpdateData) *SubscriptionTypeUpdate {
	this := SubscriptionTypeUpdate{}
	this.Data = data
	return &this
}

// NewSubscriptionTypeUpdateWithDefaults instantiates a new SubscriptionTypeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeUpdateWithDefaults() *SubscriptionTypeUpdate {
	this := SubscriptionTypeUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionTypeUpdate) GetData() SubscriptionTypeUpdateData {
	if o == nil {
		var ret SubscriptionTypeUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeUpdate) GetDataOk() (*SubscriptionTypeUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionTypeUpdate) SetData(v SubscriptionTypeUpdateData) {
	o.Data = v
}

func (o SubscriptionTypeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionTypeUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeUpdate := _SubscriptionTypeUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeUpdate)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeUpdate(varSubscriptionTypeUpdate)

	return err
}

type NullableSubscriptionTypeUpdate struct {
	value *SubscriptionTypeUpdate
	isSet bool
}

func (v NullableSubscriptionTypeUpdate) Get() *SubscriptionTypeUpdate {
	return v.value
}

func (v *NullableSubscriptionTypeUpdate) Set(val *SubscriptionTypeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeUpdate(val *SubscriptionTypeUpdate) *NullableSubscriptionTypeUpdate {
	return &NullableSubscriptionTypeUpdate{value: val, isSet: true}
}

func (v NullableSubscriptionTypeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


