/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransactionsCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionsCollectionData{}

// TransactionsCollectionData struct for TransactionsCollectionData
type TransactionsCollectionData struct {
	Type string `json:"type"`
	Attributes TransactionsCollectionDataAttributes `json:"attributes"`
}

type _TransactionsCollectionData TransactionsCollectionData

// NewTransactionsCollectionData instantiates a new TransactionsCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionsCollectionData(type_ string, attributes TransactionsCollectionDataAttributes) *TransactionsCollectionData {
	this := TransactionsCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTransactionsCollectionDataWithDefaults instantiates a new TransactionsCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionsCollectionDataWithDefaults() *TransactionsCollectionData {
	this := TransactionsCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *TransactionsCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TransactionsCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TransactionsCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TransactionsCollectionData) GetAttributes() TransactionsCollectionDataAttributes {
	if o == nil {
		var ret TransactionsCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TransactionsCollectionData) GetAttributesOk() (*TransactionsCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TransactionsCollectionData) SetAttributes(v TransactionsCollectionDataAttributes) {
	o.Attributes = v
}

func (o TransactionsCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionsCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TransactionsCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionsCollectionData := _TransactionsCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionsCollectionData)

	if err != nil {
		return err
	}

	*o = TransactionsCollectionData(varTransactionsCollectionData)

	return err
}

type NullableTransactionsCollectionData struct {
	value *TransactionsCollectionData
	isSet bool
}

func (v NullableTransactionsCollectionData) Get() *TransactionsCollectionData {
	return v.value
}

func (v *NullableTransactionsCollectionData) Set(val *TransactionsCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionsCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionsCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionsCollectionData(val *TransactionsCollectionData) *NullableTransactionsCollectionData {
	return &NullableTransactionsCollectionData{value: val, isSet: true}
}

func (v NullableTransactionsCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionsCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


