/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionTypeCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTypeCreateDataAttributes{}

// SubscriptionTypeCreateDataAttributes struct for SubscriptionTypeCreateDataAttributes
type SubscriptionTypeCreateDataAttributes struct {
	// Name
	Name string `json:"name"`
	// Description
	Description string `json:"description"`
}

type _SubscriptionTypeCreateDataAttributes SubscriptionTypeCreateDataAttributes

// NewSubscriptionTypeCreateDataAttributes instantiates a new SubscriptionTypeCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTypeCreateDataAttributes(name string, description string) *SubscriptionTypeCreateDataAttributes {
	this := SubscriptionTypeCreateDataAttributes{}
	this.Name = name
	this.Description = description
	return &this
}

// NewSubscriptionTypeCreateDataAttributesWithDefaults instantiates a new SubscriptionTypeCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTypeCreateDataAttributesWithDefaults() *SubscriptionTypeCreateDataAttributes {
	this := SubscriptionTypeCreateDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *SubscriptionTypeCreateDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeCreateDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SubscriptionTypeCreateDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SubscriptionTypeCreateDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SubscriptionTypeCreateDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SubscriptionTypeCreateDataAttributes) SetDescription(v string) {
	o.Description = v
}

func (o SubscriptionTypeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTypeCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *SubscriptionTypeCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionTypeCreateDataAttributes := _SubscriptionTypeCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionTypeCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = SubscriptionTypeCreateDataAttributes(varSubscriptionTypeCreateDataAttributes)

	return err
}

type NullableSubscriptionTypeCreateDataAttributes struct {
	value *SubscriptionTypeCreateDataAttributes
	isSet bool
}

func (v NullableSubscriptionTypeCreateDataAttributes) Get() *SubscriptionTypeCreateDataAttributes {
	return v.value
}

func (v *NullableSubscriptionTypeCreateDataAttributes) Set(val *SubscriptionTypeCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTypeCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTypeCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTypeCreateDataAttributes(val *SubscriptionTypeCreateDataAttributes) *NullableSubscriptionTypeCreateDataAttributes {
	return &NullableSubscriptionTypeCreateDataAttributes{value: val, isSet: true}
}

func (v NullableSubscriptionTypeCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTypeCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


