/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingScheduleUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingScheduleUpdate{}

// BillingScheduleUpdate struct for BillingScheduleUpdate
type BillingScheduleUpdate struct {
	Data BillingScheduleUpdateData `json:"data"`
}

type _BillingScheduleUpdate BillingScheduleUpdate

// NewBillingScheduleUpdate instantiates a new BillingScheduleUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingScheduleUpdate(data BillingScheduleUpdateData) *BillingScheduleUpdate {
	this := BillingScheduleUpdate{}
	this.Data = data
	return &this
}

// NewBillingScheduleUpdateWithDefaults instantiates a new BillingScheduleUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingScheduleUpdateWithDefaults() *BillingScheduleUpdate {
	this := BillingScheduleUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *BillingScheduleUpdate) GetData() BillingScheduleUpdateData {
	if o == nil {
		var ret BillingScheduleUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BillingScheduleUpdate) GetDataOk() (*BillingScheduleUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BillingScheduleUpdate) SetData(v BillingScheduleUpdateData) {
	o.Data = v
}

func (o BillingScheduleUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingScheduleUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BillingScheduleUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingScheduleUpdate := _BillingScheduleUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingScheduleUpdate)

	if err != nil {
		return err
	}

	*o = BillingScheduleUpdate(varBillingScheduleUpdate)

	return err
}

type NullableBillingScheduleUpdate struct {
	value *BillingScheduleUpdate
	isSet bool
}

func (v NullableBillingScheduleUpdate) Get() *BillingScheduleUpdate {
	return v.value
}

func (v *NullableBillingScheduleUpdate) Set(val *BillingScheduleUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingScheduleUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingScheduleUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingScheduleUpdate(val *BillingScheduleUpdate) *NullableBillingScheduleUpdate {
	return &NullableBillingScheduleUpdate{value: val, isSet: true}
}

func (v NullableBillingScheduleUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingScheduleUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


