/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubPlanUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubPlanUpdate{}

// SubPlanUpdate struct for SubPlanUpdate
type SubPlanUpdate struct {
	Data SubPlanUpdateData `json:"data"`
}

type _SubPlanUpdate SubPlanUpdate

// NewSubPlanUpdate instantiates a new SubPlanUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubPlanUpdate(data SubPlanUpdateData) *SubPlanUpdate {
	this := SubPlanUpdate{}
	this.Data = data
	return &this
}

// NewSubPlanUpdateWithDefaults instantiates a new SubPlanUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubPlanUpdateWithDefaults() *SubPlanUpdate {
	this := SubPlanUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubPlanUpdate) GetData() SubPlanUpdateData {
	if o == nil {
		var ret SubPlanUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubPlanUpdate) GetDataOk() (*SubPlanUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubPlanUpdate) SetData(v SubPlanUpdateData) {
	o.Data = v
}

func (o SubPlanUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubPlanUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubPlanUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubPlanUpdate := _SubPlanUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubPlanUpdate)

	if err != nil {
		return err
	}

	*o = SubPlanUpdate(varSubPlanUpdate)

	return err
}

type NullableSubPlanUpdate struct {
	value *SubPlanUpdate
	isSet bool
}

func (v NullableSubPlanUpdate) Get() *SubPlanUpdate {
	return v.value
}

func (v *NullableSubPlanUpdate) Set(val *SubPlanUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubPlanUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubPlanUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubPlanUpdate(val *SubPlanUpdate) *NullableSubPlanUpdate {
	return &NullableSubPlanUpdate{value: val, isSet: true}
}

func (v NullableSubPlanUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubPlanUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


