/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingScheduleData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingScheduleData{}

// BillingScheduleData struct for BillingScheduleData
type BillingScheduleData struct {
	// user ID
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes BillingScheduleDataAttributes `json:"attributes"`
}

type _BillingScheduleData BillingScheduleData

// NewBillingScheduleData instantiates a new BillingScheduleData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingScheduleData(id string, type_ string, attributes BillingScheduleDataAttributes) *BillingScheduleData {
	this := BillingScheduleData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewBillingScheduleDataWithDefaults instantiates a new BillingScheduleData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingScheduleDataWithDefaults() *BillingScheduleData {
	this := BillingScheduleData{}
	return &this
}

// GetId returns the Id field value
func (o *BillingScheduleData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BillingScheduleData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BillingScheduleData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *BillingScheduleData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BillingScheduleData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BillingScheduleData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *BillingScheduleData) GetAttributes() BillingScheduleDataAttributes {
	if o == nil {
		var ret BillingScheduleDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *BillingScheduleData) GetAttributesOk() (*BillingScheduleDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *BillingScheduleData) SetAttributes(v BillingScheduleDataAttributes) {
	o.Attributes = v
}

func (o BillingScheduleData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingScheduleData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *BillingScheduleData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingScheduleData := _BillingScheduleData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingScheduleData)

	if err != nil {
		return err
	}

	*o = BillingScheduleData(varBillingScheduleData)

	return err
}

type NullableBillingScheduleData struct {
	value *BillingScheduleData
	isSet bool
}

func (v NullableBillingScheduleData) Get() *BillingScheduleData {
	return v.value
}

func (v *NullableBillingScheduleData) Set(val *BillingScheduleData) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingScheduleData) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingScheduleData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingScheduleData(val *BillingScheduleData) *NullableBillingScheduleData {
	return &NullableBillingScheduleData{value: val, isSet: true}
}

func (v NullableBillingScheduleData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingScheduleData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


