/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionPlansCollectionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPlansCollectionData{}

// SubscriptionPlansCollectionData struct for SubscriptionPlansCollectionData
type SubscriptionPlansCollectionData struct {
	Type string `json:"type"`
	Attributes SubscriptionPlansCollectionDataAttributes `json:"attributes"`
}

type _SubscriptionPlansCollectionData SubscriptionPlansCollectionData

// NewSubscriptionPlansCollectionData instantiates a new SubscriptionPlansCollectionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPlansCollectionData(type_ string, attributes SubscriptionPlansCollectionDataAttributes) *SubscriptionPlansCollectionData {
	this := SubscriptionPlansCollectionData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubscriptionPlansCollectionDataWithDefaults instantiates a new SubscriptionPlansCollectionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPlansCollectionDataWithDefaults() *SubscriptionPlansCollectionData {
	this := SubscriptionPlansCollectionData{}
	return &this
}

// GetType returns the Type field value
func (o *SubscriptionPlansCollectionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlansCollectionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubscriptionPlansCollectionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubscriptionPlansCollectionData) GetAttributes() SubscriptionPlansCollectionDataAttributes {
	if o == nil {
		var ret SubscriptionPlansCollectionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlansCollectionData) GetAttributesOk() (*SubscriptionPlansCollectionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubscriptionPlansCollectionData) SetAttributes(v SubscriptionPlansCollectionDataAttributes) {
	o.Attributes = v
}

func (o SubscriptionPlansCollectionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPlansCollectionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubscriptionPlansCollectionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionPlansCollectionData := _SubscriptionPlansCollectionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionPlansCollectionData)

	if err != nil {
		return err
	}

	*o = SubscriptionPlansCollectionData(varSubscriptionPlansCollectionData)

	return err
}

type NullableSubscriptionPlansCollectionData struct {
	value *SubscriptionPlansCollectionData
	isSet bool
}

func (v NullableSubscriptionPlansCollectionData) Get() *SubscriptionPlansCollectionData {
	return v.value
}

func (v *NullableSubscriptionPlansCollectionData) Set(val *SubscriptionPlansCollectionData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPlansCollectionData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPlansCollectionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPlansCollectionData(val *SubscriptionPlansCollectionData) *NullableSubscriptionPlansCollectionData {
	return &NullableSubscriptionPlansCollectionData{value: val, isSet: true}
}

func (v NullableSubscriptionPlansCollectionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPlansCollectionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


