/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Relationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Relationships{}

// Relationships struct for Relationships
type Relationships struct {
	Data RelationshipsData `json:"data"`
}

type _Relationships Relationships

// NewRelationships instantiates a new Relationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationships(data RelationshipsData) *Relationships {
	this := Relationships{}
	this.Data = data
	return &this
}

// NewRelationshipsWithDefaults instantiates a new Relationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationshipsWithDefaults() *Relationships {
	this := Relationships{}
	return &this
}

// GetData returns the Data field value
func (o *Relationships) GetData() RelationshipsData {
	if o == nil {
		var ret RelationshipsData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Relationships) GetDataOk() (*RelationshipsData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Relationships) SetData(v RelationshipsData) {
	o.Data = v
}

func (o Relationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Relationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Relationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationships := _Relationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRelationships)

	if err != nil {
		return err
	}

	*o = Relationships(varRelationships)

	return err
}

type NullableRelationships struct {
	value *Relationships
	isSet bool
}

func (v NullableRelationships) Get() *Relationships {
	return v.value
}

func (v *NullableRelationships) Set(val *Relationships) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationships(val *Relationships) *NullableRelationships {
	return &NullableRelationships{value: val, isSet: true}
}

func (v NullableRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


