/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubTypeUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubTypeUpdateData{}

// SubTypeUpdateData struct for SubTypeUpdateData
type SubTypeUpdateData struct {
	Type string `json:"type"`
	Attributes SubTypeUpdateDataAttributes `json:"attributes"`
}

type _SubTypeUpdateData SubTypeUpdateData

// NewSubTypeUpdateData instantiates a new SubTypeUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubTypeUpdateData(type_ string, attributes SubTypeUpdateDataAttributes) *SubTypeUpdateData {
	this := SubTypeUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubTypeUpdateDataWithDefaults instantiates a new SubTypeUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubTypeUpdateDataWithDefaults() *SubTypeUpdateData {
	this := SubTypeUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubTypeUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubTypeUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubTypeUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubTypeUpdateData) GetAttributes() SubTypeUpdateDataAttributes {
	if o == nil {
		var ret SubTypeUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubTypeUpdateData) GetAttributesOk() (*SubTypeUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubTypeUpdateData) SetAttributes(v SubTypeUpdateDataAttributes) {
	o.Attributes = v
}

func (o SubTypeUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubTypeUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubTypeUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubTypeUpdateData := _SubTypeUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubTypeUpdateData)

	if err != nil {
		return err
	}

	*o = SubTypeUpdateData(varSubTypeUpdateData)

	return err
}

type NullableSubTypeUpdateData struct {
	value *SubTypeUpdateData
	isSet bool
}

func (v NullableSubTypeUpdateData) Get() *SubTypeUpdateData {
	return v.value
}

func (v *NullableSubTypeUpdateData) Set(val *SubTypeUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubTypeUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubTypeUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubTypeUpdateData(val *SubTypeUpdateData) *NullableSubTypeUpdateData {
	return &NullableSubTypeUpdateData{value: val, isSet: true}
}

func (v NullableSubTypeUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubTypeUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


