/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionPlanCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPlanCreate{}

// SubscriptionPlanCreate struct for SubscriptionPlanCreate
type SubscriptionPlanCreate struct {
	Data SubscriptionPlanCreateData `json:"data"`
}

type _SubscriptionPlanCreate SubscriptionPlanCreate

// NewSubscriptionPlanCreate instantiates a new SubscriptionPlanCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPlanCreate(data SubscriptionPlanCreateData) *SubscriptionPlanCreate {
	this := SubscriptionPlanCreate{}
	this.Data = data
	return &this
}

// NewSubscriptionPlanCreateWithDefaults instantiates a new SubscriptionPlanCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPlanCreateWithDefaults() *SubscriptionPlanCreate {
	this := SubscriptionPlanCreate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionPlanCreate) GetData() SubscriptionPlanCreateData {
	if o == nil {
		var ret SubscriptionPlanCreateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionPlanCreate) GetDataOk() (*SubscriptionPlanCreateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionPlanCreate) SetData(v SubscriptionPlanCreateData) {
	o.Data = v
}

func (o SubscriptionPlanCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPlanCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionPlanCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionPlanCreate := _SubscriptionPlanCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionPlanCreate)

	if err != nil {
		return err
	}

	*o = SubscriptionPlanCreate(varSubscriptionPlanCreate)

	return err
}

type NullableSubscriptionPlanCreate struct {
	value *SubscriptionPlanCreate
	isSet bool
}

func (v NullableSubscriptionPlanCreate) Get() *SubscriptionPlanCreate {
	return v.value
}

func (v *NullableSubscriptionPlanCreate) Set(val *SubscriptionPlanCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPlanCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPlanCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPlanCreate(val *SubscriptionPlanCreate) *NullableSubscriptionPlanCreate {
	return &NullableSubscriptionPlanCreate{value: val, isSet: true}
}

func (v NullableSubscriptionPlanCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPlanCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


