/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubPlanUpdateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubPlanUpdateData{}

// SubPlanUpdateData struct for SubPlanUpdateData
type SubPlanUpdateData struct {
	Type string `json:"type"`
	Attributes SubPlanUpdateDataAttributes `json:"attributes"`
}

type _SubPlanUpdateData SubPlanUpdateData

// NewSubPlanUpdateData instantiates a new SubPlanUpdateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubPlanUpdateData(type_ string, attributes SubPlanUpdateDataAttributes) *SubPlanUpdateData {
	this := SubPlanUpdateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSubPlanUpdateDataWithDefaults instantiates a new SubPlanUpdateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubPlanUpdateDataWithDefaults() *SubPlanUpdateData {
	this := SubPlanUpdateData{}
	return &this
}

// GetType returns the Type field value
func (o *SubPlanUpdateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubPlanUpdateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubPlanUpdateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SubPlanUpdateData) GetAttributes() SubPlanUpdateDataAttributes {
	if o == nil {
		var ret SubPlanUpdateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SubPlanUpdateData) GetAttributesOk() (*SubPlanUpdateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SubPlanUpdateData) SetAttributes(v SubPlanUpdateDataAttributes) {
	o.Attributes = v
}

func (o SubPlanUpdateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubPlanUpdateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SubPlanUpdateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubPlanUpdateData := _SubPlanUpdateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubPlanUpdateData)

	if err != nil {
		return err
	}

	*o = SubPlanUpdateData(varSubPlanUpdateData)

	return err
}

type NullableSubPlanUpdateData struct {
	value *SubPlanUpdateData
	isSet bool
}

func (v NullableSubPlanUpdateData) Get() *SubPlanUpdateData {
	return v.value
}

func (v *NullableSubPlanUpdateData) Set(val *SubPlanUpdateData) {
	v.value = val
	v.isSet = true
}

func (v NullableSubPlanUpdateData) IsSet() bool {
	return v.isSet
}

func (v *NullableSubPlanUpdateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubPlanUpdateData(val *SubPlanUpdateData) *NullableSubPlanUpdateData {
	return &NullableSubPlanUpdateData{value: val, isSet: true}
}

func (v NullableSubPlanUpdateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubPlanUpdateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


