/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionUpdate{}

// SubscriptionUpdate struct for SubscriptionUpdate
type SubscriptionUpdate struct {
	Data SubscriptionUpdateData `json:"data"`
}

type _SubscriptionUpdate SubscriptionUpdate

// NewSubscriptionUpdate instantiates a new SubscriptionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionUpdate(data SubscriptionUpdateData) *SubscriptionUpdate {
	this := SubscriptionUpdate{}
	this.Data = data
	return &this
}

// NewSubscriptionUpdateWithDefaults instantiates a new SubscriptionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionUpdateWithDefaults() *SubscriptionUpdate {
	this := SubscriptionUpdate{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionUpdate) GetData() SubscriptionUpdateData {
	if o == nil {
		var ret SubscriptionUpdateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionUpdate) GetDataOk() (*SubscriptionUpdateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SubscriptionUpdate) SetData(v SubscriptionUpdateData) {
	o.Data = v
}

func (o SubscriptionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionUpdate := _SubscriptionUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionUpdate)

	if err != nil {
		return err
	}

	*o = SubscriptionUpdate(varSubscriptionUpdate)

	return err
}

type NullableSubscriptionUpdate struct {
	value *SubscriptionUpdate
	isSet bool
}

func (v NullableSubscriptionUpdate) Get() *SubscriptionUpdate {
	return v.value
}

func (v *NullableSubscriptionUpdate) Set(val *SubscriptionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionUpdate(val *SubscriptionUpdate) *NullableSubscriptionUpdate {
	return &NullableSubscriptionUpdate{value: val, isSet: true}
}

func (v NullableSubscriptionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


