openapi: 3.0.0
info:
  description: User storage service for recovery flow
  title: User storage service
  version: 0.0.1
servers:
- url: /
paths:
  /test:
    post:
      operationId: test
      responses:
        "201":
          description: Ok
      summary: Test
components:
  schemas:
    SubType:
      properties:
        data:
          $ref: '#/components/schemas/SubType_data'
      required:
      - data
      type: object
    SubTypesCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/SubType/properties/data'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    SubTypeUpdate:
      properties:
        data:
          $ref: '#/components/schemas/SubTypeUpdate_data'
      required:
      - data
      type: object
    SubPlan:
      properties:
        data:
          $ref: '#/components/schemas/SubPlan_data'
      required:
      - data
      type: object
    SubPlansCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/SubPlan/properties/data'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    SubPlanUpdate:
      properties:
        data:
          $ref: '#/components/schemas/SubPlanUpdate_data'
      required:
      - data
      type: object
    Subscription:
      properties:
        data:
          $ref: '#/components/schemas/Subscription_data'
      required:
      - data
      type: object
    SubscriptionsCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Subscription/properties/data'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    SubscriptionUpdate:
      properties:
        data:
          $ref: '#/components/schemas/SubscriptionUpdate_data'
      required:
      - data
      type: object
    PaymentMethod:
      properties:
        data:
          $ref: '#/components/schemas/PaymentMethod_data'
      required:
      - data
      type: object
    PaymentMethodsCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/PaymentMethod/properties/data'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    BillingSchedule:
      properties:
        data:
          $ref: '#/components/schemas/BillingSchedule'
      required:
      - data
      type: object
    BillingSchedulesCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/BillingSchedulesCollection_data_inner'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    BillingScheduleUpdate:
      properties:
        data:
          $ref: '#/components/schemas/BillingScheduleUpdate_data'
      required:
      - data
      type: object
    Transaction:
      properties:
        data:
          $ref: '#/components/schemas/Transaction_data'
      required:
      - data
      type: object
    TransactionsCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Transaction/properties/data'
          type: array
        links:
          $ref: '#/components/schemas/LinksPagination'
      required:
      - data
      - links
      type: object
    LinksSelf:
      properties:
        self:
          description: Link to resources
          type: string
        update:
          description: Link to update resources
          type: string
      required:
      - self
      type: object
    LinksDirect:
      properties:
        links:
          $ref: '#/components/schemas/LinksDirect_links'
        data:
          $ref: '#/components/schemas/LinksDirect_data'
      required:
      - links
      type: object
    LinksPagination:
      properties:
        previous:
          description: Link to the previous page
          type: string
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      required:
      - self
      type: object
    SubType_data_attributes:
      properties:
        name:
          description: Name
          type: string
        description:
          description: Description
          type: string
        status:
          description: Status
          type: string
        updated_at:
          description: Updated At
          format: date-time
          type: string
        created_at:
          description: Created At
          format: date-time
          type: string
      required:
      - created_at
      - description
      - name
      - status
      - updated_at
      type: object
    SubType_data:
      properties:
        id:
          description: Subscription type ID
          format: uuid
          type: string
        type:
          enum:
          - subscription_type
          type: string
        attributes:
          $ref: '#/components/schemas/SubType_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    SubTypeUpdate_data_attributes:
      properties:
        name:
          description: Name
          type: string
        status:
          description: Status
          type: string
        updated_at:
          description: Updated At
          format: date-time
          type: string
      type: object
    SubTypeUpdate_data:
      properties:
        type:
          enum:
          - subscription_type_update
          type: string
        attributes:
          $ref: '#/components/schemas/SubTypeUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    SubPlan_data_attributes:
      properties:
        type_id:
          description: Subscription Plan ID
          format: uuid
          type: string
        name:
          description: Subscription Plan Name
          type: string
        desc:
          description: Subscription Plan Description
          type: string
        price:
          description: Subscription Plan Price
          format: float64
          type: number
        currency:
          description: Subscription Plan Currency
          type: string
        billing_cycle:
          description: Subscription Plan Billing Interval
          type: string
        billing_interval:
          description: Subscription Plan Billing Interval
          type: integer
        status:
          description: Subscription Plan Status
          enum:
          - active
          - inactive
          type: string
        updated_at:
          description: Subscription Plan Updated At
          format: date-time
          type: string
        created_at:
          description: Subscription Plan Created At
          format: date-time
          type: string
      required:
      - billing_cycle
      - billing_interval
      - created_at
      - currency
      - desc
      - name
      - price
      - status
      - type_id
      - updated_at
      type: object
    SubPlan_data:
      properties:
        id:
          description: Subscription Plan ID
          format: uuid
          type: string
        type:
          enum:
          - subscription_plan
          type: string
        attributes:
          $ref: '#/components/schemas/SubPlan_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    SubPlanUpdate_data_attributes:
      properties:
        name:
          description: Name
          type: string
        desc:
          description: Description
          type: string
        price:
          description: Price
          type: number
        currency:
          description: Currency
          type: string
        status:
          description: Status
          type: string
      type: object
    SubPlanUpdate_data:
      properties:
        type:
          enum:
          - subscription_plan_update
          type: string
        attributes:
          $ref: '#/components/schemas/SubPlanUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    Subscription_data_attributes:
      properties:
        plan_id:
          description: Plan ID
          format: uuid
          type: string
        payment_method_id:
          description: Payment Method ID
          format: uuid
          type: string
        status:
          description: State
          enum:
          - active
          - inactive
          - canceled
          - expired
          type: string
        availability:
          description: Availability
          enum:
          - available
          - unavailable
          - removed
          type: string
        start_at:
          description: Start at
          format: date-time
          type: string
        updated_at:
          description: Updated at
          format: date-time
          type: string
        created_at:
          description: Created at
          format: date-time
          type: string
      required:
      - availability
      - created_at
      - payment_method_id
      - plan_id
      - start_date
      - status
      - updated_at
      type: object
    Subscription_data:
      properties:
        id:
          description: User ID
          format: uuid
          type: string
        type:
          enum:
          - subscriber
          type: string
        attributes:
          $ref: '#/components/schemas/Subscription_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    SubscriptionUpdate_data_attributes:
      properties:
        plan_id:
          description: Plan ID object ID
          format: ObjectId
          type: string
        status:
          description: Status
          enum:
          - active
          - inactive
          - cancelled
          type: string
        payment_method_id:
          description: Payment Method ID
          format: uuid
          type: string
      type: object
    SubscriptionUpdate_data:
      properties:
        type:
          enum:
          - subscriber_update
          type: string
        attributes:
          $ref: '#/components/schemas/SubscriptionUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    PaymentMethod_data_attributes:
      properties:
        user_id:
          description: User ID
          format: uuid
          type: string
        type:
          enum:
          - payment_method
          type: string
        provider_token:
          description: Provider token
          type: string
        is_default:
          description: Is default
          type: boolean
        created_at:
          description: Created at
          example: 2020-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - created_at
      - is_default
      - provider_token
      - type
      - user_id
      type: object
    PaymentMethod_data:
      properties:
        id:
          description: payment method ID
          format: uuid
          type: string
        type:
          enum:
          - payment_method
          type: string
        attributes:
          $ref: '#/components/schemas/PaymentMethod_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    BillingSchedulesCollection_data_inner:
      properties:
        id:
          description: schedules ID
          format: uuid
          type: string
        type:
          enum:
          - billing_schedule
          type: string
        attributes:
          $ref: '#/components/schemas/BillingScheduleUpdate/properties/data/properties/attributes'
      required:
      - attributes
      - id
      - type
    BillingScheduleUpdate_data_attributes:
      properties:
        user_id:
          description: User ID
          format: uuid
          type: string
        schedules_date:
          description: Billing Schedule Date
          format: date-time
          type: string
        attempted_date:
          description: Billing Schedule Attempted Date
          format: date-time
          type: string
        status:
          description: Billing Schedule Status
          enum:
          - active
          - inactive
          type: string
        updated_at:
          description: Billing Schedule Updated At
          format: date-time
          type: string
        created_at:
          description: Billing Schedule Created At
          format: date-time
          type: string
      required:
      - created_at
      - schedules_date
      - status
      - updated_at
      - user_id
      type: object
    BillingScheduleUpdate_data:
      properties:
        type:
          enum:
          - billing_schedule_update
          type: string
        attributes:
          $ref: '#/components/schemas/BillingScheduleUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    Transaction_data_attributes:
      properties:
        user_id:
          description: User ID
          format: uuid
          type: string
        plan_id:
          description: Plan ID
          format: ObjectId
          type: string
        payment_id:
          description: Payment ID
          format: ObjectId
          type: string
        amount:
          description: Transaction amount
          format: float
          type: number
        currency:
          description: Transaction currency
          type: string
        provider_transaction_id:
          description: Provider transaction ID
          type: string
        transaction_date:
          description: Transaction creation date
          format: date-time
          type: string
      required:
      - amount
      - currency
      - payment_id
      - plan_id
      - provider_transaction_id
      - transaction_date
      - user_id
      type: object
    Transaction_data:
      properties:
        id:
          description: Transaction ID
          format: uuid
          type: string
        type:
          enum:
          - transaction
          type: string
        attributes:
          $ref: '#/components/schemas/Transaction_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    LinksDirect_links:
      properties:
        self:
          description: Link to participants
          type: string
        related:
          description: Link to participants
          type: string
      required:
      - data
      - related
      - self
      type: object
    LinksDirect_data:
      properties:
        id:
          description: resources id
          type: string
        type:
          description: resources type
          type: string
      required:
      - id
      - type
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
