openapi: 3.0.0
info:
  title: User storage service
  description: User storage service for recovery flow
  version: 0.0.1
paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: Ok
components:
  schemas:
    SubType:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: Subscription type ID
            type:
              type: string
              enum:
                - subscription_type
            attributes:
              type: object
              required:
                - name
                - description
                - status
                - updated_at
                - created_at
              properties:
                name:
                  type: string
                  description: Name
                description:
                  type: string
                  description: Description
                status:
                  type: string
                  description: Status
                updated_at:
                  type: string
                  format: date-time
                  description: Updated At
                created_at:
                  type: string
                  format: date-time
                  description: Created At
    SubTypesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SubType/properties/data'
        links:
          $ref: '#/components/schemas/LinksPagination'
    SubTypeUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - subscription_type_update
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: Name
                status:
                  type: string
                  description: Status
                updated_at:
                  type: string
                  format: date-time
                  description: Updated At
    SubPlan:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: Subscription Plan ID
            type:
              type: string
              enum:
                - subscription_plan
            attributes:
              type: object
              required:
                - type_id
                - name
                - desc
                - price
                - currency
                - billing_cycle
                - billing_interval
                - status
                - updated_at
                - created_at
              properties:
                type_id:
                  type: string
                  format: uuid
                  description: Subscription Plan ID
                name:
                  type: string
                  description: Subscription Plan Name
                desc:
                  type: string
                  description: Subscription Plan Description
                price:
                  type: number
                  format: float64
                  description: Subscription Plan Price
                currency:
                  type: string
                  description: Subscription Plan Currency
                billing_cycle:
                  type: string
                  description: Subscription Plan Billing Interval
                billing_interval:
                  type: integer
                  description: Subscription Plan Billing Interval
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: Subscription Plan Status
                updated_at:
                  type: string
                  format: date-time
                  description: Subscription Plan Updated At
                created_at:
                  type: string
                  format: date-time
                  description: Subscription Plan Created At
    SubPlansCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SubPlan/properties/data'
        links:
          $ref: '#/components/schemas/LinksPagination'
    SubPlanUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - subscription_plan_update
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: Name
                desc:
                  type: string
                  description: Description
                price:
                  type: number
                  description: Price
                currency:
                  type: string
                  description: Currency
                status:
                  type: string
                  description: Status
    Subscription:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: User ID
            type:
              type: string
              enum:
                - subscriber
            attributes:
              type: object
              required:
                - plan_id
                - payment_method_id
                - status
                - availability
                - start_date
                - updated_at
                - created_at
              properties:
                plan_id:
                  type: string
                  format: uuid
                  description: Plan ID
                payment_method_id:
                  type: string
                  format: uuid
                  description: Payment Method ID
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                    - canceled
                    - expired
                  description: State
                availability:
                  type: string
                  enum:
                    - available
                    - unavailable
                    - removed
                  description: Availability
                start_at:
                  type: string
                  format: date-time
                  description: Start at
                updated_at:
                  type: string
                  format: date-time
                  description: Updated at
                created_at:
                  type: string
                  format: date-time
                  description: Created at
    SubscriptionsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Subscription/properties/data'
        links:
          $ref: '#/components/schemas/LinksPagination'
    SubscriptionUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - subscriber_update
            attributes:
              type: object
              properties:
                plan_id:
                  type: string
                  format: ObjectId
                  description: Plan ID object ID
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                    - cancelled
                  description: Status
                payment_method_id:
                  type: string
                  format: uuid
                  description: Payment Method ID
    PaymentMethod:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: payment method ID
            type:
              type: string
              enum:
                - payment_method
            attributes:
              type: object
              required:
                - user_id
                - type
                - provider_token
                - is_default
                - created_at
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: User ID
                type:
                  type: string
                  enum:
                    - payment_method
                provider_token:
                  type: string
                  description: Provider token
                is_default:
                  type: boolean
                  description: Is default
                created_at:
                  type: string
                  format: date-time
                  description: Created at
                  example: '2020-01-01T00:00:00Z'
    PaymentMethodsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethod/properties/data'
        links:
          $ref: '#/components/schemas/LinksPagination'
    BillingSchedule:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/BillingSchedule'
    BillingSchedulesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            required:
              - id
              - type
              - attributes
            properties:
              id:
                type: string
                format: uuid
                description: schedules ID
              type:
                type: string
                enum:
                  - billing_schedule
              attributes:
                $ref: '#/components/schemas/BillingScheduleUpdate/properties/data/properties/attributes'
        links:
          $ref: '#/components/schemas/LinksPagination'
    BillingScheduleUpdate:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - billing_schedule_update
            attributes:
              type: object
              required:
                - user_id
                - schedules_date
                - status
                - updated_at
                - created_at
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: User ID
                schedules_date:
                  type: string
                  format: date-time
                  description: Billing Schedule Date
                attempted_date:
                  type: string
                  format: date-time
                  description: Billing Schedule Attempted Date
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: Billing Schedule Status
                updated_at:
                  type: string
                  format: date-time
                  description: Billing Schedule Updated At
                created_at:
                  type: string
                  format: date-time
                  description: Billing Schedule Created At
    Transaction:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: Transaction ID
            type:
              type: string
              enum:
                - transaction
            attributes:
              type: object
              required:
                - user_id
                - plan_id
                - payment_id
                - amount
                - currency
                - provider_transaction_id
                - transaction_date
              properties:
                user_id:
                  type: string
                  format: uuid
                  description: User ID
                plan_id:
                  type: string
                  format: ObjectId
                  description: Plan ID
                payment_id:
                  type: string
                  format: ObjectId
                  description: Payment ID
                amount:
                  type: number
                  format: float
                  description: Transaction amount
                currency:
                  type: string
                  description: Transaction currency
                provider_transaction_id:
                  type: string
                  description: Provider transaction ID
                transaction_date:
                  type: string
                  format: date-time
                  description: Transaction creation date
    TransactionsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Transaction/properties/data'
        links:
          $ref: '#/components/schemas/LinksPagination'
    LinksSelf:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          description: Link to resources
        update:
          type: string
          description: Link to update resources
    LinksDirect:
      type: object
      required:
        - links
      properties:
        links:
          type: object
          required:
            - self
            - related
            - data
          properties:
            self:
              type: string
              description: Link to participants
            related:
              type: string
              description: Link to participants
        data:
          type: object
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: resources id
            type:
              type: string
              description: resources type
    LinksPagination:
      type: object
      required:
        - self
      properties:
        previous:
          type: string
          description: Link to the previous page
        self:
          type: string
          description: Link to the current page
        next:
          type: string
          description: Link to the next page
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
