openapi: 3.0.0
info:
  title: User storage service
  description: User storage service for recovery flow
  version: 0.0.1

paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: "Ok"

components:
  schemas:
    SubType:
        $ref: './spec/components/schemas/SubType.yaml'
    SubTypesCollection:
      $ref: './spec/components/schemas/SubTypesCollection.yaml'
    SubTypeUpdate:
      $ref: './spec/components/schemas/SubTypeUpdate.yaml'
    SubPlan:
      $ref: './spec/components/schemas/SubPlan.yaml'
    SubPlansCollection:
      $ref: './spec/components/schemas/SubPlansCollection.yaml'
    SubPlanUpdate:
      $ref: './spec/components/schemas/SubPlanUpdate.yaml'
    Subscription:
      $ref: './spec/components/schemas/Subscription.yaml'
    SubscriptionsCollection:
      $ref: './spec/components/schemas/SubscriptionCollection.yaml'
    SubscriptionUpdate:
      $ref: './spec/components/schemas/SubscriptionUpdate.yaml'
    PaymentMethod:
      $ref: './spec/components/schemas/PaymentMethod.yaml'
    PaymentMethodsCollection:
      $ref: './spec/components/schemas/PaymentMethodsCollection.yaml'
    BillingSchedule:
      $ref: './spec/components/schemas/BillingSchedule.yaml'
    BillingSchedulesCollection:
      $ref: './spec/components/schemas/BillingSchedulesCollection.yaml'
    BillingScheduleUpdate:
      $ref: './spec/components/schemas/BillingScheduleUpdate.yaml'
    Transaction:
      $ref: './spec/components/schemas/Transaction.yaml'
    TransactionsCollection:
      $ref: './spec/components/schemas/TransactionsCollection.yaml'
    LinksSelf:
      $ref: './spec/components/schemas/LinksSelf.yaml'
    LinksDirect:
      $ref: './spec/components/schemas/LinksDirect.yaml'
    LinksPagination:
      $ref: './spec/components/schemas/LinksPagination.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT