// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package core

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BillingSchedule struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ScheduledDate time.Time
	AttemptedDate sql.NullTime
	Status        string
	CreatedAt     sql.NullTime
}

type PaymentMethod struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Type          string
	ProviderToken string
	IsDefault     sql.NullBool
	CreatedAt     sql.NullTime
}

type Subscription struct {
	UserID          uuid.UUID
	PlanID          uuid.UUID
	PaymentMethodID uuid.NullUUID
	Status          string
	StartDate       time.Time
	EndDate         time.Time
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type SubscriptionCancellation struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	CancellationDate sql.NullTime
	Reason           sql.NullString
}

type SubscriptionPlan struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Price        string
	BillingCycle string
	Currency     string
	CreatedAt    sql.NullTime
}

type SubscriptionTransaction struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	PaymentMethodID uuid.NullUUID
	Amount          string
	Currency        string
	Status          string
	PaymentProvider string
	PaymentID       sql.NullString
	TransactionDate sql.NullTime
}
